### ISSUE TITLE
Permit Upload also external images!

### ISSUE THREAD

**Issue by xexiu** [volmer/bootsy#109]
Hello,
It is posible to allow the upload images togheter with the external link images?
Right now I'm using the upload method, but It would be perfect to let users posts external images links.
Waiting for your answer.
Thanks.

**Comment by volmer** [comment]
In fact there's a PR for it: #112. Thanks for the request!

**Comment by volmer** [comment]
Closed through https://github.com/volmer/bootsy/pull/112
