### ISSUE TITLE
thin problem (?)

### ISSUE THREAD

**Issue by rediver** [volmer/bootsy#110]
Hay Guys! 

I have problem when I did in console 

rails generate bootsy:install

I recived 

gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/group.rb:211:in `handle_argument_error': rails_generate insert_into_file takes 1 argument, but it should not. (ArgumentError)               
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'                                                                                               
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'                                                                                                         
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'                                                                                          
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'                                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'                                                                                                    
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'                                                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'                                                                                              
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'                                                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'                                                                                                         
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/generators.rb:157:in `invoke'                                                                                              
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/commands/generate.rb:11:in `<top (required)>'                                                                              
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'                                                                             
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'                                                                    
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'                                                                             
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'                                                                    
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:51:in `generate'                                                                                
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'                                                                            
        from /home/action/.gem/ruby/2.1.1/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'                                                                                       
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'                                                                             
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'                                                                    
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'                                                                             
        from /home/action/tail-tip/bin/rails:8:in `<top (required)>'                                                                                                                               
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'                                                                                
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `block in load'                                                                       
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                     
        from /home/action/.gem/ruby/2.1.1/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'                                                                                
        from /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                                         
        from /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                           

Any solution? 

Thanks in advance

**Comment by ravster** [comment]
I get something similar :

`
       route  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
   identical  config/locales/bootsy.en.yml
     skipped  insert into app/assets/javascripts/application.js
     skipped  insert into app/assets/stylesheets/application.css
   identical  config/initializers/bootsy.rb
ArgumentError: rails insert_into_file takes 1 argument, but it should not.
                  run at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/command.rb:27
       invoke_command at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/invocation.rb:126
           invoke_all at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/invocation.rb:133
                 each at org/jruby/RubyHash.java:1341
                  map at org/jruby/RubyEnumerable.java:763
           invoke_all at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/invocation.rb:133
             dispatch at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/group.rb:232
                start at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/thor-0.19.1/lib/thor/base.rb:440
               invoke at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/generators.rb:157
               (root) at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/generate.rb:11
              require at org/jruby/RubyKernel.java:1071
              require at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247
      load_dependency at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232
              require at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247
               (root) at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:1
  generate_or_destroy at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:135
             generate at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:51
         run_command! at /home/ravi/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40
              require at org/jruby/RubyKernel.java:1071
               (root) at bin/rails:4
`

**Comment by volmer** [comment]
Hey, thanks for reporting thanks. Sorry about that. Could you please check if it's fixed on `master`? I gave a try with 5e023f2c47e67f4906ab5353eb35daee967ad456. I will gladly release a new version of the gem with the fix.

**Comment by laurenbenichou** [comment]
I was getting the same error. I am now tracking master and I get this: 

[WARNING] Could not load generator "generators/bootsy/install_generator". Error: /Users/name/.rvm/gems/ruby-2.0.0-p598/bundler/gems/bootsy-31b7117d2da5/lib/generators/bootsy/install_generator.rb:39: syntax error, unexpected ','
      def require_asset(destination:, content:, after_line:)

**Comment by volmer** [comment]
Sorry about that. That patch wasn't Ruby 2.0 compatible, but I just fixed that. Could you please give it another try?

**Comment by laurenbenichou** [comment]
Solved! Thanks!

**Comment by volmer** [comment]
Cool, I've just release a new version with the fix (2.0.13). Thanks for contributing!
