### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by mabed** [volmer/bootsy#114]
Tried to install bootsy, A bunch of icons are missing. I think everything is hooked in the assets pipeline correctly, I do see the bootsy files when I look at the source of the page. Also when I click the upload I get error "422 Unprocessable Entity"

![bootsy](https://cloud.githubusercontent.com/assets/6341/5906429/57d9b410-a54c-11e4-8e25-0aa064ebe1a3.jpg)

**Comment by mabed** [comment]
I was missing the icons because I was using Font Awesome instead of the stock bootstrap icons. 

I'm still getting  "422 Unprocessable Entity". Any help would be greatly appreciated.

**Comment by volmer** [comment]
Hi there! I'll need more details about the error, such as logs with the stack trace. Also, could you please try the master branch?

**Comment by mabed** [comment]
Cheers, thank you for getting in touch. I used the master. Here is a screen shot followed by the log. I do have mini_magick installed and working correctly with Carrierwave 


![bootsy_master](https://cloud.githubusercontent.com/assets/6341/5924178/70f64d9c-a60e-11e4-8fbd-ad3da0be6bc4.jpg)


Started POST "/bootsy/image_galleries/129/images" for ::1 at 2015-01-27 10:18:54 -0800
Processing by Bootsy::ImagesController#create as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"WxLbXm1Ex4efYyCSUZ8GgPVX+ZzbGhjCq/GX+t9YZ1ZjAYRomWBl3DKEAWnRxat03u0RvUXT1wsJPpV0Lt9NHg==", "image"=>{"remote_image_file_url"=>"", "image_file"=>#<ActionDispatch::Http::UploadedFile:0x007fad42488220 @tempfile=#<Tempfile:/var/folders/gl/nwc8x2hd4g70_0tq663f9mtw0000gn/T/RackMultipart20150127-55571-1m83wpa.jpg>, @original_filename="strop.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"image[image_file]\"; filename=\"strop.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "remotipart_submitted"=>"true", "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"application/json, text/javascript, */*; q=0.01", "image_gallery_id"=>"129"}
  Bootsy::ImageGallery Load (0.2ms)  SELECT  "bootsy_image_galleries".* FROM "bootsy_image_galleries" WHERE "bootsy_image_galleries"."id" = $1 LIMIT 1  [["id", 129]]
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
executable not found: "identify"   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 422 Unprocessable Entity in 26ms (Views: 0.2ms | ActiveRecord: 0.5ms)

**Comment by mabed** [comment]
Oops, imagemagick wasn't installed! But after Installing it Bootsy is working, Thank again for the second set of eyes :)

**Comment by volmer** [comment]
Thanks for using Bootsy!

**Comment by mabed** [comment]
It’s a light, lovely little editor. Sorry, one more question how do I allow users to embed YouTube videos?
