### ISSUE TITLE
youtube video embed

### ISSUE THREAD

**Issue by mabed** [volmer/bootsy#115]
How do I go about allowing users to embed YouTube videos. I found this code by searching the issues, it works! But is there to make this code as a button/link, maybe open a modal, which would make the insertion transparent to the users without having to interact with the HTML?

<iframe frameborder="0" allowfullscreen="1" width="560" height="315" src="//www.youtube.com/embed/d2QdITRRMHg"></iframe>'

**Comment by volmer** [comment]
Yeah, we currently don't have any plans to implement such feature. Embedded videos only work in the HTML mode for now  😕
