### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by shabbirun** [volmer/bootsy#116]
I followed the instructions step-by-step and implemented bootsy in my rails app, but the lists icons are not showing up properly. I haven't changed any css except that of the text box itself. Any ideas? Thanks!

![screen shot 2015-01-30 at 5 52 27 pm](https://cloud.githubusercontent.com/assets/8410122/5975627/ed595932-a8a8-11e4-8a10-4a903f3f35a4.png)

    <p>Body HTML</p>
    <%= bootsy_area :article, :body_html, class: 'input-xxlarge post' %>

**Comment by shabbirun** [comment]
I have bootstrap installed.

**Comment by volmer** [comment]
Have you tried #114 and #31?

**Comment by shabbirun** [comment]
#31 was it! Thanks :)
