### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by askinss** [volmer/bootsy#117]
I upload an image which displayed in the form but displaying on show page displayed the  src url below instead of the real image.

below is what I got
h
img alt="Thumb abim" src="/uploads/bootsy/image/10/small_abim.jpg" class="wysiwyg-float-left"

**Comment by volmer** [comment]
Hey, thanks for using Bootsy. Could you please attach a screenshot of your `show` page? By the way, have checked in your database or Rails console if you have a proper HTML in your model?

**Comment by askinss** [comment]
my form

<%= form_for @post do |p| %>
    <div> <%= p.text_field :title, placeholder: 'post title' %></div>
    <div> <%= p.bootsy_area(:body).html_safe %></div>
    
  <div class='form-actions'>
    <%= p.submit %>
  </div>  
<% end %>


![bootsydispalyerror](https://cloud.githubusercontent.com/assets/4650052/5994682/241dd666-aa7d-11e4-949c-9658bfdaa03c.jpg)

Below is what was saved in the database
 select * from posts;
1|My pics|<img alt="Thumb img 20140817 122135" src="/uploads/bootsy/image/1/IMG_20140817_122135.jpg" class="wysiwyg-float-right">|2015-01-28 12:17:02.855127|2015-01-28 12:17:02.855127
2|first post|Me am here now<br><img alt="Thumb img 20140809 100212" src="/uploads/bootsy/image/2/small_IMG_20140809_100212.jpg" class="wysiwyg-float-left"><br>|2015-01-28 12:28:32.750620|2015-01-28 12:28:32.750620

**Comment by volmer** [comment]
Could you please share the code you're using to render the text in your `show` view?

**Comment by askinss** [comment]
This is the except of the erb thats displayed the screenshot I shared
  <div>
    <%= @post.title  %>
 </div>
 <div> 
   <%= @post.body   %>
 </div>

**Comment by volmer** [comment]
You need to explicitly allow your HTML content. By default Rails escapes everything. You can try the `raw` method to achieve that:

```erb
<%= raw @post.body %>
```

However you should be more explicit on what HTML elements and attributes are allowed, for security reasons. Take a look at `sanitize`: http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html

**Comment by askinss** [comment]
Thanks  it works.
