### ISSUE TITLE
Override Source URL?

### ISSUE THREAD

**Issue by zeknox** [volmer/bootsy#123]
I noticed that when uploading images using Bootsy that it will default to relative URLs for the source inside the html. Is it possible to override this default behavior somehow and make the source URL absolute so I can send HTML emails and the images still render properly outside of the application.

BTW... Bootsy is win!

**Comment by volmer** [comment]
Hey, thanks for using Bootsy. Although currently it's not possible, I think that's a good idea! I'll try to include that on Bootsy 2.1. In the meantime, you'll have to parse your content, unfortunately.

I'll keep you posted!

**Comment by sandergarretsen** [comment]
@zeknox, I ran into the same issue. This is what I did to set the full source url for uploaded images:
Set asset_host in environments `config/environments/development.rb`:
```
config.action_controller.asset_host = 'http://localhost:3000'
```

add asset_host to carrierwave initializer `config/initializers/carrierwave.rb` :

```
CarrierWave.configure do |config|
  config.asset_host = ActionController::Base.asset_host
end

**Comment by vernondegoede** [comment]
Thanks @sandergarretsen! This works like a charm.

**Comment by volmer** [comment]
Since configuring CairrerWave does the trick I think we can close this. Thanks for sharing!
