### ISSUE TITLE
Click/Unclick bold button results into inserted space

### ISSUE THREAD

**Issue by vlamanna** [volmer/bootsy#128]
If you place your cursor on the title and you press bold then press bold again, it inserts a space.

**Comment by vlamanna** [comment]
You actually have the same behaviour with the italic and underline button.

**Comment by volmer** [comment]
This is a bug on Wysihtml5, which is not maintained anymore. I'm trying to find an active fork to replace it.

**Comment by volmer** [comment]
Good news, I just moved Bootsy to Bootstrap3-wysithml5 on master! Could you please give it a try? I'm planning to release a new version soon.
