### ISSUE TITLE
Wrapping Text Around Photos

### ISSUE THREAD

**Issue by Mufc2202** [volmer/bootsy#131]
Just installed and am using Bootsy. I am wondering how I get the text to wrap around images. Your sample app has it, but I cant figure it out.
Thank you so much.

**Comment by volmer** [comment]
Hi! 

Actually you have that option for uploaded images only. After uploading an image you have a collapse menu where you can choose between `left`, `right` and `inline`. 

I'll try to extend that to external images when I update `wysihtml5`.
