### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by bublik** [volmer/bootsy#133]
Hi 
I have done 
rake bootsy:install:migrations
rake db:migrate

and included to my mode  container

class Post < ActiveRecord::Base
  include Bootsy::Container
end

added :bootsy_image_gallery_id

def post_params
  params.require(:post).permit(:title, :content, :bootsy_image_gallery_id)
end

use simple_form

 <%= f.input :content, as: :bootsy %>

and as result i see only image url, than included to content, no any uploads

what I miss for image upload?

bootsy.rb 

on default

Bootsy.setup do |config|
  config.image_versions_available = [:small, :medium, :large, :original]
end

**Comment by volmer** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by bublik** [comment]
sorry it is closed repo

**Comment by volmer** [comment]
I understand that. What I'm asking you is to create a new Rails app, install Bootsy on it and see if you get the same error. If yes, please upload it to GitHub and share it with me.

**Comment by volmer** [comment]
I'm closing this for now. Feel free to reopen it when you're able to contribute with a sample app.
