### ISSUE TITLE
Working with pre/code

### ISSUE THREAD

**Issue by iamgalaxy** [volmer/bootsy#139]
It appears that using code and pre tags is allowed, but there are no buttons/edit options for it and as such, it's not possible to get in or out of those tags without using the source.

Are there plans to support this or is there already a way to use those tags via buttons?

I'd need to include code snippets in the display (and of course avoid XSS and the formatting) using those tags. So I believe the prerequisites are somehow already there, including sanitization of script tags, etc.

Optimal would be to allow anything between those tags to display arbitrary code, including proper HTML encoding.

Thanks a lot.

**Comment by volmer** [comment]
Have you tried to enable HTML editing? https://github.com/volmer/bootsy#enabledisable-features

**Comment by volmer** [comment]
I'm closing this for now. Feel free to reopen it if you have any issues.
