### ISSUE TITLE
AWS s3 uploads not viewable

### ISSUE THREAD

**Issue by godzilla74** [volmer/bootsy#140]
S3 uploading seem to not be viewable after upload.  Initializer is setup and working with CarrierWave (through other models not utilizing bootsy).  The file is uploaded to S3, but not viewable in the UI even after saving.

**initializer/bootsy.rb**

    Bootsy.setup do |config|
      config.storage = :fog
      config.store_dir = 'uploads'
    end

![screen shot 2015-05-29 at 6 17 00 pm](https://cloud.githubusercontent.com/assets/737720/7893774/18ec393c-062f-11e5-932e-def639d323de.png)

**Comment by volmer** [comment]
You also have to install the `fog` gem and configure CarrierWave accordingly: https://github.com/carrierwaveuploader/carrierwave/tree/3a0978a390de9d96d05e5befc40b2fabc27644cc#using-amazon-s3

Also since you are not storing the files locally you don't need to setup the `store_dir`.
