### ISSUE TITLE
mini_magick dependency conflicts with CarrierWave bug workaround

### ISSUE THREAD

**Issue by abevoelker** [volmer/bootsy#142]
Just an FYI, there's currently some issues with CarrierWave when using certain features that forces one to require an old version of mini_magick (~> 3.8.0): https://github.com/carrierwaveuploader/carrierwave/issues/1520

Since bootsy requires mini_magick ~> 4.0, this causes issues with those of us that need to use the old version of mini_magick. No biggie, I made my own fork to work around it, but just wanted to let you know.

P.S. thanks for the neat gem!

**Comment by volmer** [comment]
Thanks for letting me know, I wasn't aware of that. By the way, how did you fix it? Did you just change the dependency to `>= 3.8`?

**Comment by abevoelker** [comment]
In my fork I removed the version clause since I already have it pinned in my application's Gemfile. But yeah `>= 3.8` should work.

**Comment by volmer** [comment]
Looks like this is no longer an issue on the latest versions. Thanks for the help!
