### ISSUE TITLE
HTML5 required attribute

### ISSUE THREAD

**Issue by coderbydesign** [volmer/bootsy#144]
I implemented bootsy on an textarea with required="required", and while the validations still prevent the form from submitting, the field notice for the user does not display. I assume this has something to do with the fact that the actual textarea is hidden, but has anyone come across a solution for native HTML5 validations?

**Comment by volmer** [comment]
Thanks for reporting this. I don't have a solution for this yet as it's caused by Bootstrap-wysihtml5, the underlying js library. I do have plans to replace it in a near future with a modern alternative.
