### ISSUE TITLE
Bootstrap-wysihtml5 no longer maintained

### ISSUE THREAD

**Issue by adrianoresende** [volmer/bootsy#146]
I have problem with warning in console:
`'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach). wysihtml5.js:175 `

"Bootsy is a WYSIWYG editor for Rails based on Bootstrap-wysihtml5.."
I think for this fix is using based on `bootstrap3-wysiwyg`, check README of repo `Bootstrap-wysihtml5`:
`This repo is no longer maintained. bootstrap3-wysiwyg is much better`

**Comment by volmer** [comment]
Yeah, I receive complaints about that almost every week lol
I'll change it to a modern alternative in a near future. Stay tuned for new releases soon!

**Comment by volmer** [comment]
Good news, I just moved Bootsy to Bootstrap3-wysithml5 on master! Could you please give it a try? I'm planning to release a new version soon.
