### ISSUE TITLE
Is it possible to add mailto links in the rich text editor?

### ISSUE THREAD

**Issue by andyh** [volmer/bootsy#150]
Is there a way to add mailto links, i.e. so an email address in the content can open the users mail client. Can we either allow mailto as a valid option for links or have them automatically be linked in the resulting output?

**Comment by volmer** [comment]
Hi there,

Currently there's no way to do such thing. However you can always change the parser rules to allow `mailto` links. For more information, please take a look at the README in Bootstrap-wysihtml5 repo (especially the Parser Rules section): https://github.com/jhollingworth/bootstrap-wysihtml5#parser-rules
