### ISSUE TITLE
Disable creating image versions

### ISSUE THREAD

**Issue by janmarsicek** [volmer/bootsy#151]
Is this possible to disable creating image versions? In my `initializers/bootsy.rb` I set `config.image_versions_available = [:original]` but this affect only options when inserting image in editor. Now I can insert only original size file which is absolutely OK but I don't want other image sizes to be created (except thumb which is obviously used for thumbnail in editor) and uploaded to my S3 bucket.

Is there solution for disabling this?

Thanks!

**Comment by volmer** [comment]
Hi there,

Currently there's no config to completely disable certain versions. I know it's not optimal, but you can always monkeypatch around `Bootsy::ImageUploader` to force-exclude some keys from `.versions`.
