### ISSUE TITLE
Image upload view is locked not able to do any clicking

### ISSUE THREAD

**Issue by raysango** [volmer/bootsy#152]
Thanks for a great gem, I only have one problem when I try to upload image it will show this
<img width="812" alt="screen shot 2015-07-17 at 9 37 28 pm" src="https://cloud.githubusercontent.com/assets/9522524/8760356/113a4486-2ccc-11e5-9071-9a65040d83b0.png">

But it is disabled I'm not able to click on anything and I end up refreshing the page to get back to the view this only happens when I add the Bootsy::Container module which is a must.

Do you know what is the problem?

**Comment by volmer** [comment]
Hey, can you please provide a sample application that reproduces the problem?

**Comment by raysango** [comment]
I think I found out the reason, it was the div container css
.container {
	background-color: #FFF;
	opacity: 0.9;
}

it was kinda conflicting with image uploader view so I just removed the opacity and now I can click and upload image. do you think there is another way to solve this?

my repo: https://github.com/LARailsLearners/rayapp

**Comment by volmer** [comment]
Actually I'm asking you to create a new Rails app with the bare minimum that reproduces the problem you're facing. This way we can see if that's a bug on Bootsy or not.

**Comment by raysango** [comment]
I created a new app : https://github.com/raysango/bootsytest 
Under the routes: products/new
Same problem

**Comment by volmer** [comment]
Thanks for the app! 

In fact, the problem is the `opacity` you've added on the `.container` class, as Bootsy renders the modal for the markup inside the page container. You'll have to change your css in order to fix it.

**Comment by raysango** [comment]
Thank You
