### ISSUE TITLE
Bootsy not showing (SimpleForm - Cocoon - Bootsy)

### ISSUE THREAD

**Issue by sebabouche** [volmer/bootsy#153]
Hi, I'm having trouble with nested fields:
![bootsy-cocoon](https://cloud.githubusercontent.com/assets/6465147/8761275/ce8383f0-2d48-11e5-8bce-3c33c678afd7.jpg)
# Gems used:
https://github.com/plataformatec/simple_form
https://github.com/nathanvda/cocoon
and of course bootsy ;-)
(and slim !)
# Here is my pseudo code:
I just got rid of some unrelated fields.
## _form.html.slim
This is a form for an :offer that has_many :sections

    = simple_form_for @offer, url: provider_offers_path do |f|
        = f.input :title
        = f.input :description, as: :bootsy
    
        #sections
            = f.simple_fields_for :sections do |section|
                = render 'section_fields', :f => section
        .links
            = link_to_add_association 'Add new section', f, :sections
                  
        = f.button :submit, class:"btn-primary"

## _section_fields.html.slim

    = f.input :title
    = f.input :description, as: :bootsy

I haven't seen any answer to that problem in the previous issues or googling it :(
And no errors in the javascript console :((
If you have any idea how to deal with this kind of problem…

**Comment by sebabouche** [comment]
This issue is just for _creating_ a nested child.
When _updating_ a previously created one, bootsy bar is right there.

**Comment by volmer** [comment]
Hey, can you please provide a sample application that reproduces the problem?

**Comment by nathanvda** [comment]
Cocoon will inject form parts into the DOM, so you will have to initialise the newly added bootsy-areas after injecting. 

This is pretty simple using a `cocoon:after-insert` callback. Just do something like

     $('form').on('cocoon:after-insert', function(e, insertedItem) {
        Bootsy.init();
     });

this will initialise all non-initialised bootsy-areas.

**Comment by sebabouche** [comment]
Thanks Nathan !!!
It works like a charm. Just a small glitch but let's follow this discussion on your gem repo ;)
