### ISSUE TITLE
Insert image only via URL?

### ISSUE THREAD

**Issue by mrjoechin** [volmer/bootsy#154]
I was looking at http://bootsy-demo.herokuapp.com/ and noticed that the image icon triggers a modal that only lets you paste a url to an image. I would like the same functionality in my implementation. Is there a setting that makes this possible?

Thanks, 
Joe

**Comment by volmer** [comment]
You just need to call `bootsy_area` in a form builder not associated to a `Bootsy::Container` model. See https://github.com/volmer/bootsy#uploads
