### ISSUE TITLE
Handling security

### ISSUE THREAD

**Issue by sxjoel** [volmer/bootsy#155]
Hi , 
I hope this is the right place to discuss these things , anyway:
What are my options in regards to security? 
for example user sends to my server a link tag with an onclick method that does something malicious(For example it sends a request to delete user account)
are there any methods\gems I can use to defend myself?

Thanks!

**Comment by volmer** [comment]
Bootsy works as any input form in your application: you need to make sure you're properly handling whatever you get on the server side. When rendering back those values it's important to properly escape/sanitize accordingly. Rails already have offers a lot of helpers that you can use. I recommend you to take a look at
http://guides.rubyonrails.org/security.html
http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html
http://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html
