### ISSUE TITLE
How to add a custom style

### ISSUE THREAD

**Issue by asnad** [volmer/bootsy#156]
Can I add a custom style to bootsy lets say I want to add a font style 'disclaimer' along with heading 1, heading 2 and heading 3 with smaller font size. How can I do it?

**Comment by volmer** [comment]
Hi there!

You probably need to use custom templates in Bootstrap3-wysihtml5. Since this is beyond Bootsy's scope, I recommend you to take a look at their wiki: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/wiki/Custom-Templates
