### ISSUE TITLE
wysihtml5 not maintained anymore?

### ISSUE THREAD

**Issue by sxjoel** [volmer/bootsy#157]
https://github.com/xing/wysihtml5 The project says its not being maintained anymore and directs you to https://github.com/Voog/wysihtml.
I wanted to know if there's any plans to move to a new editor . It seems problematic to be dependent on a project that's not maintained anymore .
 The main reason I'm asking is I've been approached by colleagues about a few small bugs with the editor (For example entering more than one newline etc) and I can't expect it to be resolved if we don't move to a newer editor (correct me if I'm wrong)

**Comment by volmer** [comment]
Yes, in fact `master` now uses Bootstrap3-wysithml5 which includes the new wysihtml. A new version of the gem is coming soon, but in the meanwhile you can give `master` a try. Please let me know if you experience any issues.
