### ISSUE TITLE
Local div for the bootsy_area => css style sheet not loading.

### ISSUE THREAD

**Issue by donkeydonkey** [volmer/bootsy#160]
Hi,
Love the editor. Thanks much.
So i am using rails 4.2.4. The editor is working great so far except that it doesnt load the the local div's css, and instead it loads the the body's {css h1,h2, etc}. This makes it hard to show the client what the page will look like.. Thanks much for all your work.
Luke

**Comment by volmer** [comment]
Hi Luke,

Could you give me more details about the error? Screenshots would be great.
By the way, have you tried the `master` branch?

**Comment by donkeydonkey** [comment]
Hi,
![bootsy_1](https://cloud.githubusercontent.com/assets/10145679/9839375/e625b0f8-5a2c-11e5-8011-4985bb8066f6.jpg)

So this picture shows the editor and the the finished page. On both of these divs i have specified an h1 h2 and h3 style that should take the place of the body { h1: .h2: h3: } . 
This example is easy to see with the H2 .
the text that says "it really pays to do the groundwork"
Has a weight of 900 in the local div styling and
has a weight of 500 in the body styling. The editor is showing the body styling instead of the div styling. I applied the css style in the div outside of the form and also I tried on the div that encloses the bootsy_area. ....

i have not tried nor am i aware of the master branch...

thanks very much

**Comment by volmer** [comment]
To use the `master` branch just reference the GitHub repo in your `Gemfile`:
```ruby
gem 'bootsy', github: 'volmer/bootsy'
```
Then run `bundle update bootsy`

As there might be a lot of variables involved, could you please provide a sample app that reproduces the problem?

**Comment by donkeydonkey** [comment]
I tried using the master branch, didn't fix it. I don't have an example i can share right now.
I just tried it on another project I am using and it showing similar behavior. In the new example, 
I have a body style that has a background-image. for the main body.
when i use a bootsy_area it puts that background-image in the body of the iframe that bootsy generates for text editing.

**Comment by volmer** [comment]
It doesn't have to be your working application. When you have some time, please create a new, minimal Rails app that reproduces the problem and share the GitHub repo with me.

**Comment by donkeydonkey** [comment]
ok here ya go.
https://github.com/donkeydonkey/bootsy_style.git
thanks much,
luke

**Comment by donkeydonkey** [comment]
added the h1 styles and such to the repo.

**Comment by volmer** [comment]
Thanks so much for the sample app. I was finally able to get the problem.

Unfortunately that's the expected behaviour. The editor itself is an `iframe`, so although all your css is loaded on it, it doesn't contain your markup structure.

A possible workaround would be a separate css file to be loaded only by the editor. You would not link it to your page to avoid conflicts, and would pass it to the editor with javascript. Take a look at these docs: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg#stylesheets

**Comment by volmer** [comment]
In your sample app, try this:

* Copy whatever css you want to include in the editor to `app/assets/stylesheets/pages.scss`.
* In `config/initializers/assets.rb`, add the following to enable isolate precompilation to that asset:
```ruby
Rails.application.config.assets.precompile += %w(pages.css)
```
* In `app/assets/stylesheets/pages.coffee` include the file in the stylesheets that will be sent to the editor:
```coffeescript
Bootsy.options.stylesheets.push('/assets/pages.css')
```

Let me know if it works.

**Comment by donkeydonkey** [comment]
Thanks for the workaround. I tried it in the sample app and it is working as expected. 
Did you wrap that stylesheet injection into a bootsy function?
![bootsy_js_css](https://cloud.githubusercontent.com/assets/10145679/9959633/52411688-5dca-11e5-8e2b-9be632530b1a.jpg)
I think this solution should work for my current project. 
Thanks again for your help,
luke

**Comment by volmer** [comment]
Yes, it's just a wrapper around wysihtml5's default options: https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/editor_options.js

Glad to help.
