### ISSUE TITLE
Want to add more option in editing.

### ISSUE THREAD

**Issue by shilpi230** [volmer/bootsy#161]
I want to add more option in alignment options like center, left, right etc. Can anyone give me a hint how can i achieve so by contributing in gem itself.

**Comment by volmer** [comment]
Bootsy is built on top of [Bootstrap3-wysihtml5)(https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg). You can check their docs regarding creating custom buttons and commands and perhaps submitting a PR to them.
