### ISSUE TITLE
Casein CMS and Bootsy

### ISSUE THREAD

**Issue by marcog** [volmer/bootsy#164]
Hi,
i'm trying to use Bootsy with [Casein](https://github.com/russellquinn/casein). Everything works fine except the Image Upload functionality.  it does not show up on the modal.
[here you can find](https://github.com/marcog/mlist_test) a test app i'm trying to setup

thanks
Marco

**Comment by volmer** [comment]
Hi there,

Your app doesn't work for me:


![image](https://cloud.githubusercontent.com/assets/301187/10559062/336d82f8-74b5-11e5-80ad-e89e99cdedee.png)

**Comment by marcog** [comment]
Volmer, i'm sorry, i was  including a gem under development....
now it should be ok
Alas the problem arise inside the admin part of Casein, i think you have to set up a admin user following casein instruction.

**Comment by volmer** [comment]
You need to properly follow the usage instructions on the [README](https://github.com/volmer/bootsy#usage)

More specifically, you need to use the `bootsy_area` helper on your form builder: 

```erb
<div class="row">
	<div class="col-lg-12">
		<%= f.bootsy_area :text, rows: "20", cols: "120" %>
	</div>
</div>
```
