### ISSUE TITLE
Table Tags Being Stripped

### ISSUE THREAD

**Issue by ColinW520** [volmer/bootsy#165]
Maybe I just don't understand everything under the hood here, but I am trying to use the html `<table>` tag, in an html-enabled bootsy content area.

Here's my field setup:
```
= f.bootsy_area :content, editor_options: { link: true, html: true }, rows: 20, required: true
```

It's showing me HTML editing just fine:
![image](https://cloud.githubusercontent.com/assets/3529146/10743910/203e8f46-7c04-11e5-94e5-6f51cce85028.png)

But when I go to paste my table html (below), it coverts all the tags to `span` tags:
![image](https://cloud.githubusercontent.com/assets/3529146/10743941/5261594a-7c04-11e5-87b9-b27a03e4c834.png)

Here's my table HTML:
```
<table class="table table-striped table-hover"><thead><tr><th>Normal</th><th>Potential Early Alzheimers Disease*</th></tr></thead><tbody><tr><td>Can’t find your keys</td><td>Routinely place important items in odd places, such as keys in the fridge, wallet in dishwasher</td></tr><tr><td>Search for casual names and words</td><td>Forget names of family members and common objects, or substitute words with inappropriate ones</td></tr><tr><td>Briefly forget conversation details</td><td>Frequently forget entire conversations</td></tr><tr><td>Can’t find a recipe</td><td>Can’t follow recipe directions</td></tr><tr><td>Feel the cold more</td><td>Dress regardless of weather, wear several skirts on a warm day or shorts in a snow storm</td></tr><tr><td>Make an occasional wrong turn</td><td>Get lost in familiar places, don’t remember how you got there or how to get home</td></tr><tr><td>Feel occasionally sad</td><td>Experience rapid mood swings, from tears to rage, for no discernible reason</td></tr><tr><td colspan="2">* Please consult with a physician if you believe you may be experiencing these symptoms.</td></tr></tbody></table>
```

Does Bootsy not support the Table tag? Am I doing something wrong? I've implemented WYSIWYG elsewhere using different approaches without this problem. ( https://github.com/Nerian/bootstrap-wysihtml5-rails )

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

Can you try it on the latest master? Also, make sure to whitelist all HTML tags and attributes you want via parser options.

**Comment by ColinW520** [comment]
That did it! Thank you!

![image](https://cloud.githubusercontent.com/assets/3529146/10761711/a5a8e15e-7c90-11e5-9f47-5538aa908974.png)
