### ISSUE TITLE
add class for image 

### ISSUE THREAD

**Issue by AmirolAhmad** [volmer/bootsy#167]
is there any other way on how to add class for example: `class: "img-responsive"` to the image. because currently, when upload the image thru bootsy editor, the image are not responsive in mobile view. here is the example `http://metros.events/a/hobbies/meet-world-renowned-graffiti-artist-el-seed`

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

You can customize the parser rules to achieve that. With the latest `master` you can do something like:

```javascript
  Bootsy.options = $.extend(true, Bootsy.options, {
    parserRules: {
      classes: {
        "img-responsive": 1
      },
      tags: {
        img: {
          set_class: "img-responsive"
        }
      }
    }
  });
```

**Comment by edolivares** [comment]
Where can i add this on rails?

**Comment by volmer** [comment]
@edolivares http://guides.rubyonrails.org/asset_pipeline.html

**Comment by nrosella** [comment]
Hey @volmer great work on Bootsy - works like a charm... Except the code above ;)

I've added this in to my project as it doesn't add the 'img-responsive' class. Has anything changed since the above answer?

**Comment by Irostovsky** [comment]
Hello,
Is it possible to add support for any classes into bootsy? For example I would like to use bootstrap grid system into html editing.

**Comment by volmer** [comment]
@Irostovsky you just have to list the classes you want to add as I explained above.

**Comment by Irostovsky** [comment]
@volmer thanks for the response.
As I use bootsy for admin purpose only, I open allowing any class by adding:
1. added skipping class within ```_handleAttributes``` function (`|| allowedClasses['*']`)
```// make sure that wysihtml5 temp class doesn't get stripped out
    allowedClasses["_wysihtml5-temp-placeholder"] = 1;

    // add old classes last
    oldClasses = oldNode.getAttribute("class");
    if (oldClasses) {
      classes = classes.concat(oldClasses.split(WHITE_SPACE_REG_EXP));
    }
    classesLength = classes.length;
    for (; i<classesLength; i++) {
      currentClass = classes[i];
      if (allowedClasses[currentClass] || allowedClasses['*']) {
        newClasses.push(currentClass);
      }
    }
```

2. Use '*' to allow any class:
```
  Bootsy.options = $.extend true, Bootsy.options, parserRules:
    classes:
      '*': 1

```

I did not found good way to override `wysihtml5.dom.parse` function without money patching:
just coping wysihtml5.js into my javascript and require this changed file instead of gem's.

Is there is an option to do this(I mean override parse function) in my app JS without monkey-patching?
