### ISSUE TITLE
no generator provided after bundling gem

### ISSUE THREAD

**Issue by maceonrails** [volmer/bootsy#169]
Hi guys, 
I'm facing an issue when using this gem. i'm not get any generator for bootsy that should be execute when first time using this gem 'rails generate bootsy:install' (gem already installed). when i run those command, i get message "Could not find generator 'bootsy:install'. Maybe you meant 'devise:install', 'annotate:install' or 'layout:install'". is that normal? i'm using rails 4.2.4 and ruby 2.2.3. Thanks guys

**Comment by volmer** [comment]
Hi,

You should use Bundler to execute your commands:
```
bundle exec rails generate bootsy:install
```

**Comment by maceonrails** [comment]
Hi @volmer, thanks for your respond, but unfortunately i still got same result after using bundle exec command. and when i run 'rails generate --help' to list all available generator, there no bootsy listed on the lists. but when i look at Gemfile.lock, bootsy already there. maybe i miss something?

**Comment by maceonrails** [comment]
Hi @volmer , 
furtunately i found what make this happen. this related with ruby-gemset. when i delete .ruby-gemset file and rebundling, then all working properly. hope this can help someone else that facing same problem when using gemset. thanks
