### ISSUE TITLE
Issue with click on link in demo...

### ISSUE THREAD

**Issue by andiruleu** [volmer/bootsy#170]
I was checking out the demo, and when you click on the existing link, an "insert link" pops up, but with no link attached, and when you cancel it, the whole screen turns black.

http://bootsy-demo.herokuapp.com/

**Comment by donkeydonkey** [comment]
I get the fullscreen black as well in my app.

**Comment by volmer** [comment]
Sorry about that, I just fixed it. 

@donkeydonkey could you please use the latest `master` on your app and confirm that your issue is fixed as well?

**Comment by donkeydonkey** [comment]
Thanks. So far so good.
