### ISSUE TITLE
Adding a font color picker to bootsy

### ISSUE THREAD

**Issue by cywong** [volmer/bootsy#172]
Is it possible to add a font color picker to bootsy,  so that users may use custom colors? Do I need to modify the source of wysiwyg? And how to get started?

The existing editor_options seems to enable / disable tools only.
 
Many thanks.

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

Currently [bootstrap-wyshihtml5](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg) doesn't have a color picker. If you want to create your own you will have to hack around its APIs. I recommend you to check their docs, specially this section: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/wiki/Custom-Templates
