### ISSUE TITLE
uninitialized constant ModelName::BootsyImageGallery

### ISSUE THREAD

**Issue by vshy108** [volmer/bootsy#173]
It raised the uninitialized constant error when doing following line in view

``` <%= f.bootsy_area :content %> ```

If i remove the following line in my model class  

``` include Bootsy::Container ```

then the error will not be raised.

By the way, may I know the association between my model objects with Bootsy image galleries?

My model objects should has_one, has_many or belongs_to  Bootsy image gallery?

**Comment by vshy108** [comment]
The association is 
 
 has_many :bootsy_image_galleries, as: :bootsy_resource

After I put this in model, then the error removed.

**Comment by volmer** [comment]
No, it's a `has_one` association: https://github.com/volmer/bootsy/blob/master/lib/bootsy/container.rb

I never saw such error before, might be something specific to your environment. Let me know if you need further help.

**Comment by vshy108** [comment]
Finally I know the association is defined in the module....
And I know the cause for mentioned error is because I explicitly declare the association again in the Model class. thanks
