### ISSUE TITLE
[Question] File uploads

### ISSUE THREAD

**Issue by wraithseeker** [volmer/bootsy#174]
In the demo app for Bootsy at http://bootsy-demo.herokuapp.com/, images are inserted into the post via urls while in the app it mentions that it supports file uploads for posts.

Does the gem provide an image upload for users locally through carrierwave but it is just not included in the demo?

**Comment by volmer** [comment]
Yes, I'm aware of that issue. I still need to configure a file storage for the demo app. Meanwhile it only allows images via URLs.
