### ISSUE TITLE
Missing data-wysihtml5-dialog-action="cancel" in close of insert link modal

### ISSUE THREAD

**Issue by vshy108** [volmer/bootsy#175]
Instead of 

``` 
<a class="close" data-dismiss="modal">×</a>
```

it should be 

```
<a class="close" data-dismiss="modal" data-wysihtml5-dialog-action="cancel">×</a>
```

to let the add link button can open the modal with only one click next time

**Comment by volmer** [comment]
Again, this is an issue on Bootstrap-wysihtml5. There's nothing to be done on Bootsy's side. I'm planning on moving to another js library on the next major release.
