### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by vshy108** [volmer/bootsy#176]
After click add link/image button and close its modal and click the buttons again, will have that error in console of chrome. I click the error link, it link me to this part

```
  focus: function() {
    if (this.element.ownerDocument.querySelector(":focus") === this.element) {
      return;
    }

    try { this.element.focus(); } catch(e) {}
  },
```

**Comment by volmer** [comment]
This is a known issue on Bootstrap-wysihtml5: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/105

There's nothing to be done on Bootsy's side. I'm planning on moving to another js library on the next major version.

**Comment by berhalak** [comment]
Well, try changing line number 14705 in all.js

`          dialog.on('hide', function() {
            $(this.container).modal('hide');
            setTimeout(editor.composer.focus, 0);
          });`

to
`  dialog.on('hide', function() {
            $(this.container).modal('hide');
            setTimeout(function () {
                editor.composer.focus.call(editor.composer);
            }, 0);
          });`
I think, here the scope is being lost.
