### ISSUE TITLE
Insert Image button unresponsive

### ISSUE THREAD

**Issue by sarvin** [volmer/bootsy#179]
bootsy appears to be working properly but the 'insert image' button is unresponsive (all other buttons appear to work properly).

Using Safari v9.0.2
No Javascript warnings or errors. 
I'm seeing the same 3 CSS Warnings:
Unexpected CSS token: :     dropdown.less:121
Unexpected CSS token: :     gradients.less:12
Unexpected CSS token: :     opacity.less:4

kms> bundle show bootsy
/Users/SCoachbuilder/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsy-2.2.1

kms> bundle show carrierwave
/Users/SCoachbuilder/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/carrierwave-0.10.0

kms> bundle show mini_magick
/Users/SCoachbuilder/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mini_magick-4.3.6

Novice front-end developer and new to RoR etc. (let me know if there's more information required).

**Comment by volmer** [comment]
Just tried it on Safari and it works as expected. You can test it on the demo application: http://bootsy-demo.herokuapp.com

I'm assuming its a problem with your installation. More specifically, with the way (or the order) you're requiring Bootsy on your application's asset pipeline. Can you share the content of your `app/assets/javascripts/application.js` and `app/assets/stylesheets/application.css`?

**Comment by sarvin** [comment]
app/assets/javascripts/application.js
//= require jquery                                                                                   
//= require jquery_ujs                                                                               
//= require turbolinks                                                                               
//= require_tree .
//= require bootstrap                                                                                
//= require bootsy

app/assets/stylesheets/application.css
 *= require_self
 *= require bootstrap
 *= require bootsy

**Comment by volmer** [comment]
On your `application.js`, you should `require_tree .` as a last step, so your local js won't interfere on the vedored ones. Also, where's Bootstrap coming from? Is it from the [bootstrap-sass](https://github.com/twbs/bootstrap-sass) gem? If so, you should double-check its README to see the proper way of requiring it: https://github.com/twbs/bootstrap-sass#a-ruby-on-rails

**Comment by volmer** [comment]
I'm closing this as it is not an issue on Bootsy itself, but don't hesitate on pinging me again if you need further help.
