### ISSUE TITLE
Install Generator Fails: "No such middleware to insert after: ActionDispatch::ParamsParser"

### ISSUE THREAD

**Issue by CyberStrike** [volmer/bootsy#183]
Executing `bundle exec rails generate bootsy:install` on Rails 5.0.0.beta1.1 causes this error.

```sh
.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta1.1/lib/
action_dispatch/middleware/
stack.rb:99:in `assert_index': No such middleware to 
insert after: ActionDispatch::ParamsParser (RuntimeError))
```

I tried 4.2.5 which works just fine so definitely something that changed in Rails 5 that's causing this.

**Comment by CyberStrike** [comment]
Maybe some :sparkling_heart: from @tenderlove could help solve this?

**Comment by volmer** [comment]
Thanks for reporting! I didn't yet started upgrading Bootsy to Rails 5 but this will be addressed shortly.

**Comment by AndreasWurm** [comment]
this comes from remotipart, see JangoSteve/remotipart#139

**Comment by volmer** [comment]
Thanks for the info!

**Comment by volmer** [comment]
Thanks all for your patience. This issue is now fixed as Bootsy no longer depends on Remotipart.
