### ISSUE TITLE
Feature Request: Separate field for featured image that works with image selector

### ISSUE THREAD

**Issue by PascalPencil** [volmer/bootsy#185]
Would love to see this, right now I handle featured images separately but would love to use the image library + selector that comes with bootsy for this purpose

**Comment by volmer** [comment]
I didn't quite get the feature you're proposing. Can you please elaborate?

**Comment by PascalPencil** [comment]
I use a second field in my form for a featured image, my users don't understand why it doesn't use the same popup as bootsy for image upload and selection

**Comment by PascalPencil** [comment]
Changed to automatically select first image in a post using #35 :dart:
