### ISSUE TITLE
Disabled bootsy_area and ...

### ISSUE THREAD

**Issue by sureseam** [volmer/bootsy#186]
Firstly, I have a 'disabled' bootsy_area which still allows the keyboard cursor to land and editting to occur.  It is possible to work around this but it is odd.

Secondly, there are still iframes in use and much of CSS refers to wysihtml5.  Having read much of the issue backlog: is there an imminent update?

**Comment by volmer** [comment]
> Firstly, I have a 'disabled' bootsy_area which still allows the keyboard cursor to land and editting to occur. It is possible to work around this but it is odd.

Bootsy currently does not 100% support disabled inputs. Sorry about that.

> Secondly, there are still iframes in use and much of CSS refers to wysihtml5. Having read much of the issue backlog: is there an imminent update?

I'm actually planning on moving out of Wysihtml5 since its integration with Bootstrap, known as Bootstrap-wysithml5, is long abandoned.
