### ISSUE TITLE
Shared Image Galleries on Model

### ISSUE THREAD

**Issue by chrismahon** [volmer/bootsy#187]
Hi, have a quick question regarding image galleries. I've got Bootsy all setup (great gem, thanks!) and have it associated to a Post model as in your example.

In Post #1 I clicked on the Image icon and uploaded a new image, that works great. When I go to Post #2 and clicked on the Image icon I was expecting to see the image I uploaded to Post #1 available to choose from the list of uploaded images, however the list of images is empty.

Perhaps this functionality isn't possible with Bootsy but I just wanted to know if there was a way to share images uploaded between items in the same Model?

At the moment it appears to be loading a new image gallery every Post:

**Post #1**
http://localhost:3000/bootsy/images?image_gallery_id=1&_=1455793419301

**Post #2**
http://localhost:3000/bootsy/images?image_gallery_id=2&_=1455793514437

Thanks,
Chris

**Comment by volmer** [comment]
Hi! Thanks for using Bootsy.

By default images are scoped by `Bootsy::Container`, so if each post is a container, they won't be able to share images between them.

To achieve the behaviour you want you will need another saved Active Record somewhere that includes `Bootsy::Container`, that you can reference as the container on your `bootsy_area` calls:

```erb
f.bootsy_area :body, container: @my_global_container
```

Let me know if you have any questions!
