### ISSUE TITLE
Input only reaching half of the text area

### ISSUE THREAD

**Issue by lksevans12** [volmer/bootsy#188]
Hi,

My issue is that the text is only filling up half of the text area.

Any ideas on whats happening?

![screen shot 2016-02-19 at 4 22 01 pm](https://cloud.githubusercontent.com/assets/11245958/13189366/f071c27a-d724-11e5-9bf1-3ddda605f137.png)

Thanks
Laura

**Comment by volmer** [comment]
Hi! Can you provide a sample application that reproduces the error?

**Comment by lksevans12** [comment]
https://github.com/lksevans12/sample_app

**Comment by lksevans12** [comment]
Fixed it.

**Comment by volmer** [comment]
Yeah, I just cloned it, the problem was the misusage of BS grid system.

**Comment by lksevans12** [comment]
Do you know why its like that? I extended the grid, but it still doesn't go the whole way.

**Comment by lksevans12** [comment]
Oh I see, its already bootstrap compatible, I dont need to add any classes?

**Comment by volmer** [comment]
It really depends on what you want to achieve. By default Bootsy works fine when you want it rendered on a full line. However, if you want to have responsive columns you can rely on the grid system, but you want to make sure that you're using the proper classes to have enough spacein all screen sizes. More info: http://getbootstrap.com/css/#grid

**Comment by lksevans12** [comment]
Thanks, I appreciate all your help. Love bootsy :)

**Comment by volmer** [comment]
:heart:
