### ISSUE TITLE
Images using AWS link

### ISSUE THREAD

**Issue by g00dL00Ks** [volmer/bootsy#189]
Hi! I love your plug-in.  we are using it b/c it provides the perfect tool between a full CMS but still allowing editing.

I added my images to the blog from AWS, but seems the bootsy tool keeps converting it back to a locally stored image.  I don't want to installed carrierwave gem b/c we are using paperclip throughout the site and I'm worried about conflicts.

Is there anyway to tell bootsy to just leave it hosted on AWS and not convert it to a locally sourced file?

thanks

**Comment by volmer** [comment]
Hi there! Thanks for using Bootsy.

If you don't want to store the images using the editor and just reference them via URL you can do so by disabling the upload feature: https://github.com/volmer/bootsy#uploads

**Comment by g00dL00Ks** [comment]
Thanks for your quick reply.

Just to be clear, we are only using AWS links but the bootsy editor is converting them to local files.  

Also, can you give an example of what this means?  It's not clear to me:
```
Uploads

If you don't want to have image uploads, just call bootsy_area in a form builder not associated to a Bootsy::Container model. This way users will still be able to insert images in the text area using an external image URL.
```

I'm currently using bootsy for my blog pages.  Here is my code - how do I change the code to address your suggestion?

```
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :image, label: "Blog image", :as => :file %>
    <%= f.input :title %>
    <%= f.input :content, as: :bootsy, :input_html => { :rows => 50} %>
    <%= f.input :publish, as: :boolean, label: "Do you want to publish this blog?" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline p-t-10 p-b-10 m-b-10' %>
  </div>
<% end %>

```


How would I change this to address your suggestion?

thanks again for the help

**Comment by g00dL00Ks** [comment]
Hi
So I was able to change my form to the following:
```
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :image, label: "Blog image", :as => :file %>
    <%= f.input :title %>
    <%= f.input :publish_date %>
    <%= f.input :content, as: :bootsy, editor_options: { image: false, html: true }, :input_html => { :rows => 50} %>
    <%= f.input :publish, as: :boolean, label: "Do you want to publish this blog?" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline p-t-10 p-b-10 m-b-10' %>
  </div>
<% end %>
```

And I removed from blog.rb
`include Bootsy::Container`

I can then insert an image into the Bootsy HTML editor.  However this is a very clunky solution. When working with the HTML it doesn't accept pasted input very well and has limited options.

**Can you please tell me if there is a way I can continue to use the image tool, insert a link, and have it NOT change it to a bootsy saved file. But instead keep it as an AWS link.**

thanks for your help1

**Comment by volmer** [comment]
> how do I change the code to address your suggestion?

You just need to remove `include Bootsy::Container` from your `Blog` model. That way you would still be able to insert images in the editor, but with URLs instead of uploads. You will have essentially this modal:

<img width="595" alt="screen shot 2016-03-02 at 6 47 25 pm" src="https://cloud.githubusercontent.com/assets/301187/13479759/3caccf46-e0a7-11e5-99b2-1bd3ee358212.png">

**Comment by g00dL00Ks** [comment]
Got it -I did that as well but it doesn't allow then for the same editing functionality (essentially allowing the text to wrap around the image)

Is there anyway to disable bootsy from changing the default url to /uploads/bootsy/image/...
and just get it to leave in the AWS URL provided?

thanks

**Comment by volmer** [comment]
Unfortunately not. The image positioning options are only available to uploaded images for now.

**Comment by g00dL00Ks** [comment]
Ok great - thanks for your help.  I love your tool so I'm hoping to find a good solution for this.
