### ISSUE TITLE
Paperclip support?

### ISSUE THREAD

**Issue by MrSkinny** [volmer/bootsy#190]
The readme says you can use Bootsy with Amazon S3 if you configure fog. I'm using paperclip for my image handler.  Is it not compatible?

**Comment by volmer** [comment]
Hi there! 

Bootsy uses [CarrierWave](https://github.com/carrierwaveuploader/carrierwave). You can create a CarrierWave initializer and configure Fog accordingly: https://github.com/carrierwaveuploader/carrierwave#fog

**Comment by PascalPencil** [comment]
Hahaha
