### ISSUE TITLE
CSS imported but styles broken?

### ISSUE THREAD

**Issue by MrSkinny** [volmer/bootsy#191]
Any thoughts on this? I'm using the Foundation CSS framework.

<img width="745" alt="screen shot 2016-03-09 at 10 58 01 am" src="https://cloud.githubusercontent.com/assets/3757471/13646801/fe33a570-e5e5-11e5-9f85-dd26fc2bfca6.png">

**Comment by volmer** [comment]
Sorry, as described on the README Bootsy requires Boostrap 3.

**Comment by MrSkinny** [comment]
Missed that -- appreciate the quick replies.

**Comment by volmer** [comment]
:smile:
