### ISSUE TITLE
bootsy leaves empty folders in public/uploads/bootsy/image

### ISSUE THREAD

**Issue by StanlyShauro** [volmer/bootsy#192]

**Comment by StanlyShauro** [comment]
Garbage is left in DB and in the storage after deleting the post or loading image without creating the post. I've found the way to remove it by using:

>Bootsy::ImageGallery.destroy_orphans(0.day.ago)

But bootsy still leaves empty folders in public/uploads/bootsy/image

**Comment by volmer** [comment]
Hi there!

Yes, you can delete them with `destroy_orphans`. You can even set it up as a cron task.

As for the empty folders, that's a known issue from CarrierWave, unfortunately: https://github.com/carrierwaveuploader/carrierwave/issues/222

**Comment by StanlyShauro** [comment]
Thanks for so fast answer!

Maybe you are able to use this cleanup solution, aren't you? 
or 
Is there a way I can implement this code in my app?

https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Make-a-fast-lookup-able-storage-directory-structure
