### ISSUE TITLE
Link to S3 different

### ISSUE THREAD

**Issue by PascalPencil** [volmer/bootsy#193]
I'm importing a WP blog to Bootsy-powered posts and have run into an issue that you might better understand then we do:

When importing a post, we generate an image gallery, scan the body of the post for image links, then import them to bootsy:
```ruby
require 'action_view'
require 'nokogiri'

namespace :wordpress do
  desc 'Import Worpress Posts'

  task import_posts: :environment do |_, _args|
    Bootsy::ImageGallery.destroy_all
    Bootsy::Image.destroy_all
    Article.destroy_all
    counters = {articles: 0, images: 0, bootsy_image: 0}
    errors = []
    File.open('lib/post.xml') do |file|
      items = Nokogiri::XML(file).xpath('//channel//item')
      items.first(3).each do |item|
        begin
          counters[:articles] += 1
          article = Article.create(
            title: item.at_xpath('title').text.strip,
            shorthand: item.at_xpath('wp:post_name').text.strip,
            body: item.at_xpath('content:encoded').text,
            bootsy_image_gallery: Bootsy::ImageGallery.create
          )
          article.save(validate: false)
          article.update_column(:created_at, item.at_xpath('wp:post_date_gmt').text)
          images = item.at_xpath('content:encoded').text.scan(/"([a-z\-_0-9\/\:\.]*\.(jpg|jpeg|png|gif))"/i)
          if images.any?
            amount_of_images = 0
            images.each do |image|
              counters[:images] += 1
              bootsy_image = Bootsy::Image.new(remote_image_file_url: image.first.sub(/^http:/, 'https:'), image_gallery: article.bootsy_image_gallery)
              if bootsy_image.valid?
                article.bootsy_image_gallery.images << bootsy_image
                article.update_column(:body, article.body.gsub(image.first, article.bootsy_image_gallery.images[amount_of_images].image_file.large.url).gsub(image.first.sub(/^http:/, 'https:'), article.bootsy_image_gallery.images[amount_of_images].image_file.large.url).gsub(image.first.sub(/^https:/, 'http:'), article.bootsy_image_gallery.images[amount_of_images].image_file.large.url))
                article.save(validate: false)
                counters[:bootsy_image] += 1
                amount_of_images += 1
              else
                errors << "article #{article.id}, bootsy_image failed; #{bootsy_image.errors.full_messages.join('. ')}"
              end
            end
            article.save
          end
        rescue StandardError => e
          puts "#{e}"
          next
        end
      end
    end
    puts "Status:"
    counters.each_pair { |k, v| puts "#{k}: #{v}"}
    if errors.present?
      puts "Errors: #{errors.count}"
      errors.each { |e| puts e }
    end
  end
end
```

On line 34, we replace the original URL with the new Bootsy URL generated after import, per example, this will yield:
`https://rommydebommy.s3.amazonaws.com/uploads/bootsy/image/382/large_img_2628.jpg`
In the body of the articles, which is correct.

However, when calling 
`article.bootsy_image_gallery.images.first.image_file.large.url`
inside of our views (to load as background image) the resulting output is:
`https://rommydebommy.s3.amazonaws.com/uploads/bootsy/image/image_file/382/large_img_2628.jpg`

The difference between the two is that one has `/image_file` in the link whereas the other does not, the correct link is the one without `/image_file`

I hope this is sufficient information for you to be able to tell us if there's anything obvious we're missing.

Thank you for creating and maintaining Bootsy, our clients greatly enjoy your work, as do we!

**Comment by volmer** [comment]
Hello!

It's really hard to tell for sure, but it might be related with the environment you're running the task vs the one you're serving the views. Did you check if you have distinct S3 settings on them?

Also, what happens if you reload the image records?

```ruby
image = gallery.images.new
image.remote_image_file_url = 'https://domain.com/image.png'
image.save!
image.reload.image_file.large.url
# => ???
```

**Comment by PascalPencil** [comment]
Thank you for your swift reply, we're looking into it, it would seem logical as locally it works fine, will update.

パスカル・フルステーヘン
創設者
スーパーペンシル
デザインも、ホームページ作りもアプリ作成も.
www.superpencil.com/ja

**Comment by PascalPencil** [comment]
We opted for `.sub(/\/image_file/, "")` as we're in a rush, might loop back to this later

**Comment by PascalPencil** [comment]
I had 

```ruby
-# app/uploaders/image_uploader.rb

module Bootsy
  class ImageUploader < CarrierWave::Uploader::Base
    def store_dir
      "uploads/#{model.class.to_s.underscore}/#{model.id}"
    end
  end
end
```

Which was being used only in the `production` environment, unsure why! fixed!
