### ISSUE TITLE
Murder on the dancefloor

### ISSUE THREAD

**Issue by PascalPencil** [volmer/bootsy#197]
I think this line https://github.com/volmer/bootsy/blob/master/app/uploaders/bootsy/image_uploader.rb#L11 makes any portrait-format image look very blurry.

Original:
![img_1451 1](https://cloud.githubusercontent.com/assets/3094044/14318469/f5ae4702-fc47-11e5-839c-7ee1d0973573.JPG)

Large:
![large_img_1451](https://cloud.githubusercontent.com/assets/3094044/14318474/f98d7550-fc47-11e5-9980-aeed42d38d2c.JPG)

**Comment by PascalPencil** [comment]
@volmer or am I missing a setting?

**Comment by PascalPencil** [comment]
Same issue, was doing double processing! Sorry @volmer!

**Comment by volmer** [comment]
Glad to know you managed to fix it! Sorry for the delay :bow:
