### ISSUE TITLE
something went wrong when uploading image 

### ISSUE THREAD

**Issue by khirul** [volmer/bootsy#198]
when im using bootsy::container, popup something went wrong appear when i want to upload image

here my repo https://github.com/khirul/inspirasi.git

link im using bootsy
http://localhost:3000/posts/new
dont know what happen, im using many times before without problem
thanks

**Comment by volmer** [comment]
That's a known issue happening to people using Sprockets >= 3. The easiest way to fix it is to lock it on ~> 2.3. Do this on your Gemfile and run `bundle install`:

```ruby
gem 'sprockets-rails', '~> 2.3'
```

**Comment by ThreeFingerDesigns** [comment]
@volmer I am getting the same popup error when trying to upload an image with Bootsy, even with using the 2.3 version of sprockets-rails as suggested. If I remove the `include Bootsy::Container` from `class Post < ActiveRecord::Base` I have the option for image upload via URL as expected, but the features of uploading from my local drive, as well as, choosing the image size and placement as demonstrated in the Bootsy demo is what makes this gem awesome.

Everything else works perfectly.

My repo is a private bitbucket, but I can copy and paste associated files if need be.

Thanks for any help.

**Comment by volmer** [comment]
Hey @ThreeFingerDesigns, this problem has been solved in the latest Bootsy version. Now you can use the latest `sprockets-rails`. Please upgrade Bootsy in your app.
