### ISSUE TITLE
Image upload is not working but I am able to see the image. 

### ISSUE THREAD

**Issue by abhishek-99tests** [volmer/bootsy#199]
I am trying to upload image using bootsy. But getting this error - ActionController::ParameterMissing - param is missing or the value is empty: image: . remote_image_file_url is coming blank. Please help me.

**Comment by volmer** [comment]
In which version of Rails are you at? Can you share the Rails logs of the request?

**Comment by volmer** [comment]
Closing this for now. Feel free to reopen it if you need further assistance.
