### ISSUE TITLE
Error ImageMagick/GraphicsMagick is not installed when MiniMagic works from console

### ISSUE THREAD

**Issue by lakehouseru** [volmer/bootsy#200]
Hello!

I've installed Bootsy on a local machine and staging server smoothly, but after deploy on a production I get the same error after file upload:

`<textarea data-type="application/json" data-status="422" data-statusText="Unprocessable Entity">{"image_file":["Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: ImageMagick/GraphicsMagick is not installed"]}</textarea>`

MiniMagick works fine from console - resized and saved image  
Reinstalled Imagemagick
Checked PATH variables

Any ideas what's wrong?

Thank you!

**Comment by lakehouseru** [comment]
Fixed it! The problem was that Rails app doesn't see environment PATH variable.  More details can be found here http://stackoverflow.com/questions/25267626/rails-passenger-cant-execute-shell-commands

**Comment by volmer** [comment]
Glad you fixed it! 😄
