### ISSUE TITLE
Bootsy Not Appearing

### ISSUE THREAD

**Issue by LizBayardelle** [volmer/bootsy#207]
I followed all of the installation instructions, restarted the server, ran a bundle update...and I still cannot get Bootsy to appear.  Here is my form field:

```
<%= form_for(@post) do |f| %>
 ...
  <div class="field">
    <%= f.label :body %><br>
    <%= f.bootsy_area :body, style: "min-height: 300px" %>
  </div>
```

I put `include Bootsy::Container` in my Post model and included `:bootsy_image_gallery_id` in the strong params of my controller.  Bootsy is required in my `application.js` file.  Any ideas what I'm missing?

**Comment by volmer** [comment]
Hi! Could you please share your `Gemfile`, `application.js` and `application.css`?

**Comment by LizBayardelle** [comment]
Happily!  My `Gemfile` is:
```
source 'https://rubygems.org'

gem 'rails', '4.2.5'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development do
  gem 'sqlite3'
end

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt', '~> 3.1.7'
gem 'bootstrap-sass'
gem 'friendly_id', '~> 5.1.0'
gem 'google-analytics-rails', '1.1.0'
gem 'paperclip'
gem 'meta-tags'
gem 'bootsy'
```
My `application.js` is:
```
//= require jquery
//= require jquery_ujs
//= require_tree .
//= require bootsy
//= require turbolinks
//= require bootstrap
```
And my `application.scss` (not .css) is:
```
/*
...
 *= require_tree .
 *= require_self
 *= require bootstrap
 *= require bootsy
 */
```

**Comment by volmer** [comment]
Thanks for sharing.

Bootsy has to be required after Bootstrap and before your own scripts. So your `application.js` should be:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require bootsy
//= require_tree .
```

And for `application.css`:

```
/*
 *= require bootstrap
 *= require bootsy
 *= require_tree .
 *= require_self
 */
```

Let me know if it works!

**Comment by LizBayardelle** [comment]
Made these changes, but unfortunately still no luck.  :(

**Comment by volmer** [comment]
Oh, looks like you're importing Bootstrap through the `bootstrap-sass` gem. You have to set it up properly, according to their README: https://github.com/twbs/bootstrap-sass

First of all, in `application.js` replace `bootstrap` with `boostrap-sprockets`:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require bootsy
//= require_tree .
```

And rename `application.css` to `application.scss` and use scss's `@import` statements (you won't be able to use `require_tree`, so better import your files one-by-one):

```scss
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";
@import "my_file_1";
@import "my_file_2";
```

**Comment by LizBayardelle** [comment]
Again I made these changes (import statements instead of requires in my `application.scss` file, restructured my `application.js` file, and double checked everything was installed correctly as per the link you sent).  Unfortunately Bootsy still isn't displaying...

**Comment by volmer** [comment]
I can think of anything else that might be interfering with Bootsy... Would you be able to create a new Rails app that reproduces the error and share it on GitHub?

**Comment by LizBayardelle** [comment]
I made the repository public [https://github.com/LizBayardelle/bia](url) for now.  Any help is always appreciated.

**Comment by volmer** [comment]
Thanks. What are the steps to set it up? How can I access the page Bootsy is supposed to show up?

**Comment by LizBayardelle** [comment]
I am (evidently) very new at this, but there shouldn't be any abnormal steps to set it up (it's just a webpage).  Bootsy will be on the `posts#new` page.

**Comment by volmer** [comment]
Thanks, I was able to reproduce and fix the issue. Bootsy is not showing up because you have errors both on your JS and CSS that are happening due to the double inclusion of Bootstrap and jQuery on your app's asset pipeline.

Since you're using the `boostrap-sass` gem you don't need to have Boostrap's files under `app/assets/javascripts` or `app/assets/stylesheets`. Just require the files on `application.js` and `application.scss` and they will be served directly from the gem. Same thing for jQuery: you have `jquery-rails`, the script will come from the gem. You don't need to manually add `jquery.min.js` to your assets folder.

By removing `boostrap.js`, `boostrap.min.js`, `boostrap.css`, `boostrap.min.css` and `jquery.min.js` I got rid of the errors and Boosty got displayed correctly (on a different style though, since you customized Boostrap).

I recommend you to read the Asset Pipeline Guide, is really helpful: http://guides.rubyonrails.org/asset_pipeline.html

**Comment by LizBayardelle** [comment]
Woohoo!  You are magical.  Thank you for the help and for directing me towards the Asset Pipeline Guide.

**Comment by volmer** [comment]
Thank you for using Bootsy! ❤️

**Comment by biologistbrian** [comment]
Aye aye aye.  Maybe I'm having the same issues? All I know is I'm going nuts =)  Can't get bootsy to show up!

gemfile:
```
source 'https://rubygems.org'


gem 'medium-editor-rails'
gem 'jquery-ui-rails'
gem 'simple_form'
gem 'compass-rails'
gem 'chosen-rails'
gem 'mailboxer'
gem 'bootstrap-will_paginate'
gem 'will_paginate'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'carrierwave'
gem 'fog'
gem 'bootstrap-sass'
gem 'sprockets', '2.11.0'
gem 'sass-rails'
gem 'kaminari'
gem 'geocoder'
gem 'figaro', '>= 1.0.0'
gem "wysiwyg-rails"
gem "mini_magick"
gem 'image_magick'

gem 'bootsy'
gem 'wysiwyg_rails_simple_form'
gem 'devise', '>=3.2.4'
gem 'devise_invitable', '~> 1.5.2'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rails_12factor', group: :production
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

application.js
```
//= require jquery
//= require jquery_ujs
//= require_tree .
//= require chosen-jquery
//= require messages
//= require medium-editor
//= require bootstrap-sprockets
//= require bootsy
```

applications.scss:
```
 *
 *= require chosen
 *= require_self
 *= require_tree .
 *= require font-awesome
 */

@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";
'''

I don't have any wonky jquery or bootstrap files in my asset folder...I'm hoping I'm just overlooking something...

**Comment by volmer** [comment]
@biologistbrian you have to require external JS and CSS *before* your own files. On both `application.js` and `application.css` you are requiring Bootstrap and Bootsy after `require_tree .`

**Comment by deeps1287** [comment]
Maybe I'm having the same issues? 

my application.js

//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require bootsy
//= require_tree .


and application.scss

@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";

**Comment by grichardomi** [comment]
Hello Volmer,

Has there been any update fixes to this problem? I've tried for two days by reviewing and implement fixes with no success.  Unfortunately, sample code is not available at this time. I would appreciate any help you might be able to provide.

application.scss
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";
@import "active_admin";

 application.js
//= require bootstrap-sprockets
//= require bootsy
//= require_tree .

gemfile
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.0'
#gem 'rails', '~> 5.0'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
#gem 'sass-rails', '~> 4.0.3'
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
#gem 'coffee-rails', '~> 4.0.0'
gem 'coffee-rails'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'bundler'
gem 'country_select'
gem 'trix'
gem 'bootsy'
#gem 'bootsy', '~> 2.3', '>= 2.3.1'
#pagination gems
gem  'will_paginate', '3.1.0'
gem  'bootstrap-will_paginate', '0.0.10'
gem 'carrierwave', '~> 1.0'
gem 'mini_magick', '~> 4.3'

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

gem 'tzinfo-data'
gem 'validates_formatting_of'
gem 'activeadmin', github: 'gregbell/active_admin'
#gem 'activeadmin'
#gem 'inherited_resources', '~> 1.7'
#gem 'devise', github: 'plataformatec/devise'
gem 'devise'
gem 'rails_config'
gem 'bootstrap-sass', '3.3.6'
gem 'bootstrap-sass-extras'
gem 'simple_form'
gem 'binding_of_caller'
gem 'google-analytics-rails'
gem 'omniauth'
gem 'omniauth-facebook'

group :test do
  gem 'shoulda-matchers'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
end

group :development do
  gem 'better_errors'
  gem 'byebug'
end

**Comment by volmer** [comment]
@grichardomi apparently jQuery is missing. You probably have JS errors in your browser's console. Other than that, I would only be able to help further with a sample Rails app 😕

**Comment by grichardomi** [comment]
Tks for the response. I had since included jquery. here is the one error from the console. Can you gleem any possible solution from that:

Uncaught TypeError: Cannot read property 'locale' of undefined
    at new Bootsy.Area (area.self-719c9e5….js?body=1:12)
    at HTMLTextAreaElement.<anonymous> (init.self-6673eaf….js?body=1:14)
    at Function.each (jquery.self-bd7ddd3….js?body=1:371)
    at jQuery.fn.init.each (jquery.self-bd7ddd3….js?body=1:138)
    at Object.Bootsy.init (init.self-6673eaf….js?body=1:12)
    at init.self-6673eaf….js?body=1:32
    at dispatch (jquery.self-bd7ddd3….js?body=1:5227)
    at elemData.handle (jquery.self-bd7ddd3….js?body=1:4879)

**Comment by grichardomi** [comment]
I have a bootsy.en.yml file. Also placed content of this file into en.yml with no success.

**Comment by grichardomi** [comment]
fyi!   this.locale = $el.data('bootsy-locale') || $('html').attr('lang');
  if (!$.fn.wysihtml5.locale.hasOwnProperty(this.locale)) this.locale = 'en';

**Comment by shybovycha** [comment]
I've also noticed that when I require jQuery3 in my `application.js`, it does not work as well. Fixed by replacing `//= require jquery3` with `//= require jquery`, but still interested: does bootsy rely on such specific jQuery features? =)
