### ISSUE TITLE
Bootsy not loading any css

### ISSUE THREAD

**Issue by josephhays** [volmer/bootsy#208]
Hi!

I'm using Bootsy with Rails 4, Bootstrap and Casein CMS. I'm having an issue where Bootsy and it's JS loads, but not the CSS. My `application.scss` file is below.

```sass

*= require bootsy;

@import 'bootstrap';
@import 'bootstrap-sprockets';
```

**Comment by volmer** [comment]
Hi!

You need to import Bootsy after Bootstrap is included. Also, since you're using SCSS, you should use `@import` statements:

```scss
@import 'bootstrap';
@import 'bootstrap-sprockets';
@import 'bootsy';
```

Issue #207 might be helpful too.

**Comment by josephhays** [comment]
Hello! First off, thank you for the super speedy response! Second, unfortunately, that change still didn't work. After much trial and error (I hate git... alot), I got a repository at [https://github.com/josephhays/hear](url)

**Comment by volmer** [comment]
Hi! Just took a look at your repo and it looks like you didn't fix your `application.js` and `application.scss`. On SCSS, you need first to require `boostrap`, then `boostrap-sprockets` and finally `bootsy`. On JS, require `jquery`, `jquery-ujs`, `boostrap-sprockets` and only then `bootsy`.

**Comment by josephhays** [comment]
Alrighty, did that and still can't get it working... I am getting a routing error, `ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css")` but I can't tell where that's from.

**Comment by volmer** [comment]
Rename the file to `application.scss` (not `applications.scss`, as you currently have).

**Comment by josephhays** [comment]
It... it has been a long day. Oh my god. Thank you so much and sorry for wasting time... I'm gonna go cry in the bathroom now.

**Comment by volmer** [comment]
lol That's ok, it happens with all of us. Thanks for using Bootsy!

**Comment by josephhays** [comment]
No problem, loving it and will tell everyone I know about it. Real wuick, Casein CMS is namespaced also with its own form helpers, and using `<%= casein_text_area f, f.object, :content, as: :bootsy %>` doesn't allow the casein page to use bootsy, any thoughts?

**Comment by volmer** [comment]
Unfortunately that won't work. You can try the following instead:

```erb
<%= f.boosty_area :content %>
```

But I cannot guarantee if it will work either. Bootsy is not really tested with Casein or offers support to it.

**Comment by josephhays** [comment]
I think it may be a namespacing thing? I'll look into it and let you know if I can get it to work.
