### ISSUE TITLE
NoMethodError - undefined method `content'

### ISSUE THREAD

**Issue by InsomniaNoir** [volmer/bootsy#209]
I'm putting together a simple [Blog Application](https://github.com/InsomniaNoir/personal-blog). When I try to view my `posts#new` page I get the following error and I was not able to find any issues on it. I'm still pretty new with RoR so i'm assuming it's something small but:

`NoMethodError at /posts/new
undefined method 'content' for #<Post:0x007f9d54ec0da8>
Did you mean?  concern`

It's throwing it on my `posts/new.html.erb` code:

    <h1>New Post</h1>

    <div class="row">
      <div class="md-col-8">
        <%= form_for @post do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.bootsy_area :content %> <--- This is the line it marks
          </div>
          <div class="form-group">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>

I followed the documentation so I'm not sure where to go from here.

**Comment by volmer** [comment]
Hi!

That's because your `Post` model does not have an attribute called `content`. You probably want to use Bootsy with the `body` attribute instead:

```erb
<div class="form-group">
  <%= f.label :body %>
  <%= f.bootsy_area :body %>
</div>
```
