### ISSUE TITLE
Pasting from microsoft office removes newlines.

### ISSUE THREAD

**Issue by kourindouhime** [volmer/bootsy#212]
It works fine in wisyhtml5 0.3.0 demo on https://xing.github.io/wysihtml5/, but doesn't work on https://bootsy-demo.herokuapp.com/.

Steps to reproduce:
1. Create a new document in MS Word on Windows OS with a few lines of text.
2. Copy and paste the text into the bootsy text area.
3. Text is being pasted fine, but after a few milliseconds newlines disappear and it looks as plain formatted string.

If there's no easy fix, please let me know how can event.clipboardData be modified before passing it to bootsy. Thank you!

**Comment by kourindouhime** [comment]
This fixes it for me

      var remote_document = $(".wysihtml5-sandbox")[0].contentWindow.document;
      $(remote_document).find("body").on('paste', function(event) {
        event = e.originalEvent;
        event.reventDefault();
        var html;
        html = event.clipboardData.getData('text/plain')
        remote_document.execCommand('insertText', false, html);
        console.log(event.originalEvent.clipboardData.getData('text/plain'));
      });

**Comment by volmer** [comment]
I'm sorry, I don't have MS Office nor Windows. Could you please check if #237 fixes the issue?

**Comment by volmer** [comment]
Closing this for now. Feel free to reopen it if you still wish to discuss it.
