### ISSUE TITLE
Multiple new line characters are not entered in chrome

### ISSUE THREAD

**Issue by tonyvince** [volmer/bootsy#215]
Great job with bootsy - hats off. When testing in **chrome** I am unable to enter a second newline characters after some text.  
sometext⏎ comes to next line, when I enter(⏎) again cursor goes to next line but immediately goes back to the previous new line. Works fine with mozilla

**Comment by volmer** [comment]
Hey @tonyvince, thanks for using Bootsy. This is a known issue caused by one of Bootsy's dependencies. See #98.
