### ISSUE TITLE
Do not works in nested_form fields

### ISSUE THREAD

**Issue by om-nishu-trantor** [volmer/bootsy#216]
Hi,
I am trying to use bootsy for [nested_forms](https://github.com/ryanb/nested_form).
But it seems not to populate/initialize, can someone help me in this.
Mentioned about the issue here : http://stackoverflow.com/questions/38434751/bootsy-editor-not-working-for-nested-attribtues-added-through-nested-form-gem

**Comment by volmer** [comment]
The gem you mentioned was discontinued years ago. Please use Rails' native nested form solution instead: http://guides.rubyonrails.org/form_helpers.html#nested-forms

**Comment by om-nishu-trantor** [comment]
Is there any way to dynamically initialize bootsy editor for all text areas if they are added after page load ?

**Comment by volmer** [comment]
You can use `Bootsy.init()`: https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/init.js#L31

**Comment by om-nishu-trantor** [comment]
```javascript
$(document).on('nested:fieldAdded', function(event){
  Bootsy.init();
});
```
