### ISSUE TITLE
Bootsy area not showing wysihtml5-toolbar

### ISSUE THREAD

**Issue by tonyvince** [volmer/bootsy#217]
I have a link in my index.html.erb
`<%= link_to 'New User goal', new_t_user_goal_path %>`
which redirects to the new action that renders _form.html.erb partial (bootsy form). When this link is clicked toolbar does not appear
![bootsy_issue](https://cloud.githubusercontent.com/assets/17843050/16979483/fbc6ff38-4e7e-11e6-8adc-b18890736b47.png)

 unless we refresh the page or entering the /t_user_goals/new URL manually. On refresh  toolbar appears 
![after_refresh](https://cloud.githubusercontent.com/assets/17843050/16979580/768955e0-4e7f-11e6-88c3-36de66d27ae4.png)

Please help

**Comment by volmer** [comment]
Can you provide a sample application that reproduces the error?

**Comment by tonyvince** [comment]
This is mu application.js
```
//= require jquery
//= require typeahead
//= require jquery.validate
//= require my_alert.js
//= require sortable.js
//= require turbolinks
//= require bootstrap-sprockets
//= require bootsy
//= require jquery_ujs
//= require jquery-ui/autocomplete
//= require jquery_form
//= require jquery-readyselector
//= require bootstrap-datepicker
//= require jquery.Jcrop.js
//= require cropper.min.js
//= require staff_styling
//= require mapscript.js
//= require find_routes.js
//= require pwstrength-bootstrap-1.2.8.js
//= require t_user_address_commute_changes.js
//= require jquery.formatCurrency-1.4.0.js
//= require bootbox
//= require product_post.js
//= require moment
//= require custom.js
//= require fullcalendar
//= require fullcalendar/gcal
//= require jquery.mmenu.all.min.js
//= require chosen-jquery
//= require_tree .
//= require ja.js
//= require_directory .
```
and application.scss
```
  @import "bootstrap-sprockets";
  @import "font-awesome-sprockets";
  @import "bootstrap";
  @import "bootsy";
  @import "font-awesome";
  @import "bootstrap-datepicker3";
  @import "jquery.Jcrop";
```

**Comment by volmer** [comment]
I'd suggest you to try removing each unrelated line of your application.js to detect which JS file is causing the issue. Otherwise I can help if you provide a sample application that reproduces the error.

**Comment by volmer** [comment]
Looks like Bootsy is not yet compatible with Turbolinks 5. In the meantime you can either disable Turbolinks or call `Bootsy.init()` when the page is loaded.

**Comment by tonyvince** [comment]
Thank you. Moving bootsy up in the order does the trick
```
//= require jquery
//= require bootstrap-sprockets
//= require bootsy
```
great work with bootsy.. Hats off
