### ISSUE TITLE
how do I configure image uploads with heroku?

### ISSUE THREAD

**Issue by Broshen** [volmer/bootsy#218]
Hi, I'm developing a website using bootsy, and I'm hosting it on Heroku. However, heroku doesn't support file uploads which means every time the server restarts, I lose all of my images. I was wondering if you could point me to a resource/tutorial on how to configure bootsy to work around this.

**Comment by volmer** [comment]
You need to use an external service such as S3 to host the images, and configure the uploader accordingly. Look at CarrierWave's documentation for more details: https://github.com/carrierwaveuploader/carrierwave

**Comment by Broshen** [comment]
woah! thanks for the fast response! I was hoping there was a bootsy specific solution, but Ill try that I guess. Thanks!

**Comment by volmer** [comment]
Actually there's something to be done after you configure CarrierWave in an initializer, which is to tell Bootsy to use `fog`. Take a look at Bootsy's initializer: https://github.com/volmer/bootsy/blob/master/config/initializers/bootsy.rb#L52-L58
