### ISSUE TITLE
rails 5:  couldn't find file 'bootsy' with type 'text/scss'

### ISSUE THREAD

**Issue by sr3d** [volmer/bootsy#222]
I upgraded my Rails 4.2.2 app to Rails 5 and now I'm running into this issue:

couldn't find file 'bootsy' with type 'text/scss'
              
 *= require bootsy

Any idea?  This also happens with jquery-ui as well so I ended up commenting that out, but it's not possible with bootsy.

I'm running ruby 2.3.1 with a brand new gemset.

**Comment by volmer** [comment]
Can you provide a sample application that reproduces the error?

**Comment by sr3d** [comment]
Unfortunately the app I'm building is too complicated to extract it out.  Basically it was a 4.2 Rails app, then moving to Rails 5 I had to add the new manifest.js file.  Here's the content of manifest.js if it's of any help...


//= link_tree ../images
// link_directory ../javascripts .js
// link_directory ../stylesheets .css
//= link print.css
//= link bootstrap-email.css
//= link application.css
//= link application.js

//= link jquery-ui.js
//= link jquery-ui.css


//= link bootsy.js

**Comment by volmer** [comment]
I just installed Bootsy on a brand new Rails 5 app, and it works as expected. I'm concluding that it's no a bug in Bootsy, probably something in the app you're working on. By looking at your `manifest.js` it's clear that you're referencing CSS files on a `.js` manifest, which is problematic. CSS file should be required in your `application.css` or similar. Please follow the instructions on Bootsy's README and also read the docs about Rails' asset pipeline: http://guides.rubyonrails.org/asset_pipeline.html

**Comment by sr3d** [comment]
After some mucking around, I found out what happened.  In my Gemfile I had this

gem "sprockets", "~> 4.0.x"

This must be added somehow during the Rails 4.2 to Rails 5 upgrade, and this particular version of Sprocket was causing the issue. After commenting this line out and run "bundle update" everything started to work as expected.

Thanks!
