### ISSUE TITLE
wysihtml5 buggy... Trix?

### ISSUE THREAD

**Issue by Benjamin-Dobell** [volmer/bootsy#223]
wysihtml5 has some really peculiar behaviour[1][2], should I submit pull requests to wysihtml5 and then here, or will I be wasting my time?

I see a Trix branch which hasn't been updated in about 6 months, is the plan to migrate to Trix?

[1] https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/vendor/wysihtml5.js#L8705

This calls `fromTextareaToComposer()` repeatedly at `INTERVAL`, with `shouldParseHtml` as `undefined` (i.e. falsey), this causes the `textarea` to repeatedly have its contents updated with invalid HTML 5 e.g. `<img align='blah'/>` which is deprecated behaviour.

[2] https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/vendor/wysihtml5.js#L8687

This `sync()` method takes `shouldParseHtml`, however it is only ever called with `shouldParseHtml` as `true`. Whilst the `sync` method is publicly exposed, and could therefore be called with `false`, it doesn't really make any sense as `_observe()` explicitly looks for form submissions and calls `fromTextareaToComposer(true)`. Really, there's no case in which you'd ever want to call `fromTextareaToComposer(false)` (which is done, see above) because all it does is produce deprecated HTML5 (and doesn't represent what you'll be submitting to your server).

**Comment by volmer** [comment]
Yes, the plan is to use Trix as soon as it allows configuring the toolbar and localization (a WIP that's been halted by the Trix authors for 6 months now, more info on this PR https://github.com/basecamp/trix/pull/143). 

Wysihtml5 lacks maintenance and care by the team involved with the project, and I've been long searching for a better editor. Trix is fairly new and promising, but yeah, no answer in that PR in particular for some time now.

**Comment by Benjamin-Dobell** [comment]
@volmer I made some extremely trivial changes to wysihtml5 and wysihtml-bootstrap that make the whole situation a lot less awful. In particular `customCommand` (although still supported) is no longer necessary, you can just specify a `function` instead of `true` in the options, and it'll call that function like `customCommandCallback`.

This means you're not constrained to one custom callback. Also, I fixed some particularly odd behaviour in wysihtml5-bootstrap that only considered keys/templates for known options (in `defaultOptions`). It'll now allow any options to be specified, for example I've trivially added an `align` option with buttons left, center, right and justify.

Let me know if you're interested in pull requests for these commits:

https://github.com/Benjamin-Dobell/bootsy/commit/188ad8b505e62e950f72d4db932a151fed377851

https://github.com/Benjamin-Dobell/bootsy/commit/6f068f5ab3290aeaa02aecf9b6dbc8c79e51c3e1
