### ISSUE TITLE
Could not find generator 'bootsy:install'

### ISSUE THREAD

**Issue by hamzaaltaf** [volmer/bootsy#225]
i am using rails 4.2 after i run bundle install then when i put in the following command
rails generate bootsy:install

it says the following

Could not find generator 'bootsy:install'. Maybe you meant 'devise:install', 'ckeditor:install' or 'formtastic:install'
Run `rails generate --help` for more options.

**Comment by volmer** [comment]
Hey, there is no such generator. Please follow the instructions from README.md.
