### ISSUE TITLE
Dynamic upload directory path?

### ISSUE THREAD

**Issue by elkhan** [volmer/bootsy#227]
Thank you for the awesome gem!
Is it possible to have a dynamic storage path for local uploads? I cannot find a way to reference Post object from within bootsy.rb like I would do with carrierwave

**Comment by elkhan** [comment]
Actually for remote uploads that is S3 it is the same path pattern - uploads/bootsy...
What I am looking for is similar to carrierwave's way "uploads/#{model.class.to_s.underscore}/#{model.created_at}/..."

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

The storage dir is created by the `storage_dir` method in `Bootsy::ImageUploader`. You can monkeypatch it if you want:
https://github.com/volmer/bootsy/blob/master/app/uploaders/bootsy/image_uploader.rb#L8
