### ISSUE TITLE
Unable to view or edit existing links

### ISSUE THREAD

**Issue by blakeloverain** [volmer/bootsy#230]
The demo on the main repo ("The Hobbit") has several embedded links, but double clicking doesn't open the link box with the link. Clicking on the link icon should prompt to edit the  link, not automatically remove it. Maybe just put in a 'delete' button inside the info box? 

Also if the link resembles a URL (starts with http://), it should autofill the edit box with that rather than having to type it all over again.

**Comment by volmer** [comment]
Those are good suggestions but unfortunately I won't be able to address the in Bootsy since that behaviour comes from the underlying wysiwyg library.
