### ISSUE TITLE
Make bootsy look like your demo

### ISSUE THREAD

**Issue by Academy-of-One** [volmer/bootsy#231]
Hello, great gem and thank you so much for making it.

The problem I'm having right now is that the text area and toolbar are stuck looking like this:

http://imgur.com/a/LnCyW

I can override the height properties but it won't let me allow it to be resizeable. How do I get it to look like you have it in your site?

**Comment by volmer** [comment]
Hey, thanks for using Bootsy! 

Your text area uses whatever dimensions your css defines. The code for the demo app is available on GitHub: https://github.com/volmer/bootsy-demo/blob/master/app/views/post/show.html.erb#L10

As you can see I don't have any customizations other than using Bootstrap's `form-control` and setting `rows="12"`.

**Comment by Academy-of-One** [comment]
Thank you. So it looks just like your site when I have this:

` = f.bootsy_area :content, class: 'form-control', rows: 12`

Instead of this:

`= f.input :content, as: :bootsy, :class => "form-control"`
