### ISSUE TITLE
Is there any way to use bootsy and turbolinks together

### ISSUE THREAD

**Issue by deeps1287** [volmer/bootsy#234]
my application.js is

//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require bootsy
//= require_tree .

and application.scss

@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";

In this scenario, bootsy works only when page refreshed.. otherwise not working

**Comment by lucas-wade** [comment]
Same Here.

**Comment by volmer** [comment]
Thanks for reporting. Could you please try the latest `master` and see if the issue is fixed?

**Comment by lucas-wade** [comment]
Nice. You fixed it. What was the issue?

**Comment by volmer** [comment]
The event API Bootsy was using got removed from Turbolinks. I changed it to listen to the proper event now. I will release a new version of the gem with the fix soon.

**Comment by rodrigoejcm** [comment]
Is it already supporting turbolink? somehow i disabled the turbolink require in application.js and this problem is hot happening to me anymore

**Comment by deeps1287** [comment]
@volmer : Nice. You fixed it.
