### ISSUE TITLE
uninitialized constant Sprockets::Helper

### ISSUE THREAD

**Issue by matthewbay** [volmer/bootsy#238]
I get 

....bundle/ruby/2.3.0/gems/bootsy-0.0.4/app/uploaders/bootsy/image_uploader.rb:7:in `<class:ImageUploader>': uninitialized constant Sprockets::Helpers (NameError)

on rake db:migrate

**Comment by volmer** [comment]
Looks like you are using a very old version of the gem (`bootsy-0.0.4`).
