### ISSUE TITLE
Shared media?

### ISSUE THREAD

**Issue by geoffw8** [volmer/bootsy#239]
I can see its letting me share media per post, what about site wide?

Be great to click images and see all previously used assets.

**Comment by volmer** [comment]
You can access the image in whatever storage setting you've configured (the filesystem is the default).

If you're talking about an admin-like feature in your Rails app, you can build yourself a page that renders all `Bootsy::Image` records (or `Bootsy::ImageGallery` records if you want them grouped by container).
