### ISSUE TITLE
tables 

### ISSUE THREAD

**Issue by amundmo** [volmer/bootsy#240]
Hi,
Thanks for a nice editor! 
I´ve enabled HTML-editing, but when I add a table and go back to the WYSIWYG-editor, my html is removed...
Should this be possible? Is it some how possible to enable tables?

Thanks!

Amund.

**Comment by volmer** [comment]
Hey, thanks for using Bootsy!

By default tables are not allowed. But you can override the parser rules to allow whatever tags/attributes you'd like. See https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/editor_options.js
