### ISSUE TITLE
Bootsy filtering <a href="tel:"> tags?

### ISSUE THREAD

**Issue by vernondegoede** [volmer/bootsy#241]
What's the reason for filtering <a> tags without valid URL's? I'm trying to add a clickable phone number, but the `href` attribute is filtered...

**Comment by volmer** [comment]
That's the default behaviour from `Bootstrap-Wysihtml5`: https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/vendor/bootstrap-wysihtml5.js#L464

But you can override the parser rules and remove/change the attribute checker if you want. See https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/editor_options.js
