### ISSUE TITLE
Bootsy and Carrierwave 1.0.0 compatibility

### ISSUE THREAD

**Issue by sr3d** [volmer/bootsy#245]
Bootsy isn't compatible yet with Carrierwave 1.0.0 because in the gemspec file it's locked at 'carrierwave', '~> 0.11'

The carrierwave 1.0.0 has this version tag:

gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'

which leads to incompatibility issue.

**Comment by volmer** [comment]
Yes, that's because Carrierwave 1.0.0 is not released yet. I created a branch that supports its release candidate if you want to give it a try: https://github.com/volmer/bootsy/tree/carrierwave-1-0-0

Once Carrierwave 1.0.0 is out I'll merge it into `master`.
