### ISSUE TITLE
Bootsy not updating the input's value until there is a text change

### ISSUE THREAD

**Issue by etcook** [volmer/bootsy#246]
I'm having two problems, although I think if I solve the first one, the second one becomes moot.

1) I'm trying to use Bootsy in an interface with a live preview. This works by binding a change event to the hidden value field, which Bootsy updates with content changes. The downside is that the value isn't updated until the field loses focus, so the interface isn't as reactive as it could be. Is there a callback that Bootsy utilizes for change events? I've tried attach a keypress event to the iframe to no avail. I believe this is due to a preventDefault preventing the action from bubbling up.

2) The only time the value seems to update is if you change the actual text in the field. If you just change the color or format the text (underline, bold, etc) it doesn't seem to update the field. However, once you change the text and lose focus, everything updates as you'd expect.

Do you have some suggestions on how to get around these issues? Thanks so much for a great package.

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

I'm afraid there's no good way to achieve that due to limitations on the JS library we use. See https://github.com/xing/wysihtml5/issues/52

I hope I'll be able to replace it with something better in the future.

For now my only suggestion for you would be to try adding a "Preview" button if possible.

**Comment by etcook** [comment]
@volmer Thanks for the response. I think a preview button is a good move, considering the limitations. However, what about the color/formatting changes that aren't being updated until a text change is made? Would you consider that expected behavior? Thanks again!

**Comment by volmer** [comment]
Yes, IIRC those changes are applied only when the form is submitted. You can do that with a button too.

**Comment by etcook** [comment]
@volmer As it stands, they are updated only when the text content is updated, which is odd behavior and hard to account for. Are you suggesting a button to pull not from the hidden value, but rather from within the iframe? It seems like an odd workaround.

Let me clarify the workflow.

1) Make changes to text in field.
2) Lose focus
3) Changes are made to the hidden value field.

1) Make changes to formatting.
2) Lose focus
3) Nothing happens to the hidden value field.

1) Make changes to formatting
2) Change text
3) Lost focus
4) Both text changes AND formatting changes are made to the hidden value field.

It would seem to me that both formatting and text changes should propagate to the hidden value field equally. I don't mind adding a button to trigger the update, but the different behavior whether it's a text change and formatting change is odd.

Thanks for your consideration.

**Comment by volmer** [comment]
I totally agree, it is very odd indeed. But that's unfortunately how whysihtml5 works 😢 
there's no consistency in events nor in when the commands are applied to the actual textarea. The only moment I think you can use the output safely is after submit.
