### ISSUE TITLE
Validation failed: Bootsy resource must exist

### ISSUE THREAD

**Issue by mhdrahmoun** [volmer/bootsy#250]
Hello everybody,
I'm trying to use bootsy in my Rails app but I'm facing this problem which says "Validation failed: Bootsy resource must exist".
I read the instructions and applied it literally but when I tried to open "/posts/new" the problem occurred.

the Rails version is 5.0.0.1
thank you

**Comment by volmer** [comment]
Could you please provide a sample application that reproduces the error?

**Comment by mhdrahmoun** [comment]
Problem solved after changing  `Rails.application.config.active_record.belongs_to_required_by_default` from `true` to `false` inside `new_framework_defaults.rb` file.
And Rails version was 5.0.1 not 5.0.0.1, sorry.

**Comment by volmer** [comment]
Alright then! 😄
