### ISSUE TITLE
image upload for heroku and cloudinary

### ISSUE THREAD

**Issue by arthur-littm** [volmer/bootsy#252]
Hi, 

I'm having issues setting up the image upload of bootsy on my website, hosted on heroku. I am using cloudinary and carrierwave.

Basically it works when the storage method is in :file but every time the dynos are reset or I deploy a new version I lose all the images on the website.. To fix this I have tried to set up the fog storage method but I can't get it to work..

I have added the bootsy.rb to my initializers and changed the storage method to fog.

```
Bootsy.setup do |config|
  config.image_versions_available = [:small, :medium, :large, :original]
  config.storage = :fog
end
```

and my carrierwave initalizer looks like this:

```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider: 'cloudinary_cloud_name',
    aws_access_key_id: 'cloudinary_api_key',
    aws_secret_access_key: 'cloudinary_api_secret',
  }
end
```

I am not using aws but I can't find the right key for cloudinary fog_credentials.. 

If anyone has managed to set up bootsy with heroku and cloudinary I'd love to look at the code :)

gemfile:

```
gem 'bootsy', '2.3.1'
gem 'carrierwave'
gem 'fog'
gem 'cloudinary', '1.1.0'
```

image_uploader:

```
class ImageUploader < CarrierWave::Uploader::Base

  storage :fog

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

end
```

error in console (development):

```
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:12:in 'new': cloudinary_cloud_name is not a recognized provider (ArgumentError)
```

**Comment by volmer** [comment]
Unfortunately Fog does not support Cloudinary: http://fog.io/about/supported_services.html

Since you can't use Fog you will have to monkeypatch the `ImageUploader` class if you want to use Cloudinary. See Cloudinary's docs for more info http://cloudinary.com/documentation/rails_carrierwave
