### ISSUE TITLE
Cannot change the colour and text format

### ISSUE THREAD

**Issue by Lubard** [volmer/bootsy#253]
Hi, I'm a newbie for bootsy.
I have few questions here.

i wrap the bootsy_area inside my form.
`            <%= bootsy_area :email_content, editor_options: { link: false, lists: false, html: false, alert_unsaved: true} %>
`
which displays as
![screen shot 2017-02-13 at 5 18 15 pm](https://cloud.githubusercontent.com/assets/4156201/22872894/b11ef306-f210-11e6-9937-6d57260b2a38.png)

as the link, lists and html buttons are still there, and I cannot choose the word formatting and color selection buttons (no dropdown lists).

and there's a bootstrap error when the icons works correctly
![screen shot 2017-02-13 at 5 18 21 pm](https://cloud.githubusercontent.com/assets/4156201/22872913/e26cefee-f210-11e6-99f3-a8abe8c1bda9.png)

BTW:
how could i set the default text ?
and how could i set the size of text area?

**Comment by volmer** [comment]
Bootsy is intended to be used with form builders, not as standalone form tags. You can set any text you want just like you would do in a regular `text_area` helper. Bootsy will assume whatever size you set to the text area. Also, the errors you're are seeing appear to be from your app, not Bootsy.
