### ISSUE TITLE
Update Carrierwave to 1.0.0

### ISSUE THREAD

**Issue by adeelejaz** [volmer/bootsy#256]
Carrierwave needs to be updated to latest version. I use carrierwave but I use the latest version as bootsy depends on 0.11.

```
Bundler could not find compatible versions for gem "carrierwave":
  In Gemfile:
    carrierwave (~> 1.0.0)

    bootsy was resolved to 2.3.1, which depends on
      carrierwave (~> 0.11)
```

**Comment by volmer** [comment]
Fixed at 4b373134e3dbfb67537f0b313fb65c14c119cffd

Thanks for reporting!
