### ISSUE TITLE
Bootsy 2.4.0 doesn't work with Rails 4 anymore

### ISSUE THREAD

**Issue by mateuszgorniak** [volmer/bootsy#261]
Hi!
Last time I've tried to update Bootsy in my project I had some problems.
Output:
```
.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys': Unknown key: :optional. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :dependent, :primary_key, :inverse_of, :required, :foreign_type, :polymorphic, :touch, :counter_cache (ArgumentError)
```

Possible reason:
https://github.com/volmer/bootsy/blob/master/spec/dummy/app/models/comment.rb#L3 (`optional` is new Rails 5 feature).

Is this change expected? Is it possible to add information about this dependency? What do you think about it? :-)

**Comment by volmer** [comment]
Hi! Yes, it is intended. I'd advise you to upgrade your app to Rails 5 as soon as possible. In the meantime you can lock your Bootsy version in `2.3`.
