### ISSUE TITLE
Inline form

### ISSUE THREAD

**Issue by QuadDepo** [volmer/bootsy#263]
Hi all,

I'm quite new to Rails and maybe my there is already an answer for my question that i coudlnt find that easly. But here it comes:

I added the bootsy_area to my form but some reason its showing up like this

![image](https://cloud.githubusercontent.com/assets/18424315/23835243/3c626516-0764-11e7-86c8-60fdb750e897.png)

Any idea How i could fix this?

Also the color tab isn't working. maybe that has something to do with my own css or did anyone also experience  the same problem?

**Comment by volmer** [comment]
There's definitely something messy in your assets. It could be your JS or CSS. I'd advise you to read the Rails Guides for the Asset Pipeline: http://guides.rubyonrails.org/asset_pipeline.html

Also, if you're installing Bootstrap with a gem, make sure that you're following the exact installation instructions: https://github.com/twbs/bootstrap-sass#a-ruby-on-rails

**Comment by QuadDepo** [comment]
Allright thats what i thought I fixed it by just adding the css from the github in a scss file. 


But how do i get the text area bigger
