### ISSUE TITLE
options for links (target=_blank, nofollow)

### ISSUE THREAD

**Issue by gcrofils** [volmer/bootsy#264]
Disclaimer : I guess my question is pretty common and might has been asked/replied already. Unfortunately I can't find any reference.

It seems that all links inserted within the editor are `target="_blank" rel="nofollow"`

Even if modified in HTML mode.

is there any parameter to change it ?

Thank you.

**Comment by volmer** [comment]
That's controlled by WysiHTML5's parser rules: https://github.com/xing/wysihtml5/blob/master/parser_rules/simple.js#L24

You can extend them if you want:

```
  Bootsy.options = $.extend(true, Bootsy.options, {
    parserRules: {
      tags: {
        a: {
          set_attributes: {
            target: ''
          }
        }
      }
    }
  });
```

**Comment by gcrofils** [comment]
Once again : Perfect !Thank you so much @volmer for your prompt reply !
