### ISSUE TITLE
Problem with heroku - it doesn't show the toolbar

### ISSUE THREAD

**Issue by jcarrionramos** [volmer/bootsy#269]
Hi!

I have some issues with bootsy in heroku, it doesn't show the toolbar, however it is visible in localhost. 

Attachment screenshot of application.scss

<img width="791" alt="captura de pantalla 2017-04-07 a las 10 49 41" src="https://cloud.githubusercontent.com/assets/22088059/24803298/2bffa784-1b81-11e7-88fa-cfbabd5d7022.png">

Attachment screenshot of applitacion.js

<img width="761" alt="captura de pantalla 2017-04-07 a las 10 49 54" src="https://cloud.githubusercontent.com/assets/22088059/24803311/3c841fb8-1b81-11e7-81dd-8077e70d71a4.png">

Also after executing push execute the command asset:precompile.
I could observe that in my localhost in body the wysihtml5-supported class is added, however in heroku this class is not added.

Cheers!!

**Comment by volmer** [comment]
See the documentation about Bootstrap SASS and how to properly import it: https://github.com/twbs/bootstrap-sass

You need to remove that block of comments from your `application.scss` and import all your files using `@import` statements. Also, `bootstrap-sass` needs to be imported *before* `bootstrap`, according to the instructions I listed above.

**Comment by jvaldebenito** [comment]
Hi,

Volmer I have the same problem, in my localhost it works correctly, while in heroku the toolbar is not displayed.

Attached my `application.scss` file:

<img width="466" alt="captura de pantalla 2017-04-13 a las 16 41 14" src="https://cloud.githubusercontent.com/assets/19960911/25021292/1009ebac-2068-11e7-82f5-c63c9bbfddd6.png">

Attached my `application.js` file:

<img width="955" alt="captura de pantalla 2017-04-13 a las 16 42 51" src="https://cloud.githubusercontent.com/assets/19960911/25021349/450a148a-2068-11e7-924d-04c7636ff31c.png">

Thank you!
