### ISSUE TITLE
List required Rails version in Requirements

### ISSUE THREAD

**Issue by mlaco** [volmer/bootsy#271]
Bootsy uses the `optional` option of Rails' `belongs_to`, which is only available in Rails 5. It would be helpful if the precise Rails version requirement was listed in the requirements section of your README.

**Comment by volmer** [comment]
Rails 4 and older are no longer supported by the Rails Core Team. Our README assumes that by now everybody already upgraded to Rails 5.

**Comment by jamonholmgren** [comment]
I disagree with this assumption. The Rails Core team still supports 4.2.x:

![image](https://cloud.githubusercontent.com/assets/1479215/25142475/d5501542-241b-11e7-82eb-9cd676aec0d3.png)

Not only that, but we have many clients with legacy code bases that we support, from 2.x all the way to 4.x.

@mlaco isn't asking for 4.x support. Just a note in the readme so we know not to waste time trying to get Bootsy to work.

**Comment by volmer** [comment]
> I disagree with this assumption. The Rails Core team still supports 4.2.x

The link you referred to is outdated. See https://github.com/rails/rails/blob/master/guides/source/maintenance_policy.md

> we have many clients with legacy code bases that we support, from 2.x all the way to 4.x.

I'd recommend you to encourage your clients to update those applications asap, then.

> @mlaco isn't asking for 4.x support. Just a note in the readme so we know not to waste time trying to get Bootsy to work.

Alright, then. I listed "Rails 5" in the Requirements section: https://github.com/volmer/bootsy#requirements

**Comment by jamonholmgren** [comment]
Thank you, appreciate it.
