### ISSUE TITLE
Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by koobraelc** [volmer/bootsy#65]
Hi there, 

I am using Bootsy with Twitter-bootswatch-rails with Rails4 and Ruby2.1, but it seems something wrong here. I just got this error message when I run it in Chrome. 

I already checked assets pipeline, jquery and everything else, but it still didn't work. Any similar issue?

Error:
```
Uncaught TypeError: undefined is not a function bootsy.js?body=1:273
Bootsy.Area.init bootsy.js?body=1:273
(anonymous function) init.js?body=1:22
jQuery.extend.each jquery.js?body=1:385
jQuery.fn.jQuery.each jquery.js?body=1:138
Bootsy.init init.js?body=1:12
(anonymous function) init.js?body=1:31
fire jquery.js?body=1:3100
self.fireWith jquery.js?body=1:3212
jQuery.extend.ready jquery.js?body=1:3424
completed
```

Gemfile
```
source 'https://rubygems.org'
ruby "2.1.2"

gem 'rails', '4.1.0'
group :development do
  gem 'sqlite3'
end
group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'newrelic_rpm' 
end

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'paperclip'
gem 'bootsy'
gem 'therubyracer'
gem 'twitter-bootswatch-rails', '~> 3.1.1'
gem 'rails_admin'
gem 'forem', :github => "radar/forem", :branch => "rails4"
gem 'kaminari', '0.15.1'
gem 'will_paginate', '3.0.5'
gem 'mailboxer'
```

application.js
```
//= require jquery
//= require jquery_ujs
//= require bootsy
//= require turbolinks
```

application.css
```
 *= require_self
 *= require flatly/loader
 *= require flatly/bootswatch
 *= require bootsy
```

**Comment by zenkovnick** [comment]
I've the same problem, can you explain what can cause this issue?

application.js

//= require jquery
//= require homepage
//= require jquery.cycle2
//= require jquery_ujs
//= require jquery.ui.all
//= require jquery.feedback_me
//= require jquery-fileupload/basic
//= require fcbk_complete
//= require URI
//= require markitup
//= require markitup/sets/xbbcode/set
//= require bootsy
//= require_tree .

**Comment by volmer** [comment]
@koobraelc it would be nice if you could share your findings about this bug, it would be very helpful to other people who's facing the same problem.

**Comment by lukerollans** [comment]
@koobraelc Care to share? Experiencing the same issue...

**Comment by jshow** [comment]
same here - blocked - I'm seeing the same issue.. thanks

**Comment by volmer** [comment]
Does anyone mind to provide a sample application that reproduces the issue, so I can investigate?

**Comment by jshow** [comment]
I'll pull one together tonite - thank you

**Comment by jshow** [comment]
@volmer , this app demonstrates the issue

https://github.com/jshow/boosty_ticket_65

[vagrant@localhost /vagrant/boosty_ticket_65 (master)]$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
[vagrant@localhost /vagrant/boosty_ticket_65 (master)]$ rails --version
Rails 4.2.0

I tried to limit the Gemfile. Let me know if I can help

thanks

J

**Comment by lukerollans** [comment]
@jshow @volmer awesome, thanks. let me know if I can help in any way. Super keen on getting this fixed

**Comment by volmer** [comment]
Hey, thanks for the sample app, @jshow. 

The error happens because you're requiring `jquery` and `jquery-ujs` twice in your pages. 

You have two javascript manifests: [`application.js`](https://github.com/jshow/boosty_ticket_65/blob/master/app/assets/javascripts/application.js) and
[`spacelab.js`](https://github.com/jshow/boosty_ticket_65/blob/master/app/assets/javascripts/spacelab.js), and you're requiring jQuery on both, for all your pages. 

By removing those entries on `spacelab.js` Bootsy worked as expected. I'd advice you to have only one manifest for all your javascripts, though.

**Comment by lukerollans** [comment]
Hmm. doesn't seem to be the cause of my issue. Definitely only requiring jQuery once in my only manifest

**Comment by jshow** [comment]
ah man, yes - I was using a bootswatch theme and it was including jquery without my knowledge

thank you @volmer 

@lukerollans , let me know if you want to use my app to demo your issue
